program T2TiERPContasReceber;

uses
  Forms,
  Windows,
  Dialogs,
  Tipos in '..\Comum\Tipos.pas',
  Conversor in '..\Comum\Conversor.pas',
  NotificationService in '..\Comum\NotificationService.pas',
  SessaoUsuario in '..\Comum\SessaoUsuario.pas',
  UsuarioController in '..\Comum\Controller\UsuarioController.pas',
  Controller in '..\Comum\Controller\Controller.pas',
  FuncaoController in '..\Comum\Controller\FuncaoController.pas',
  PapelController in '..\Comum\Controller\PapelController.pas',
  PapelFuncaoController in '..\Comum\Controller\PapelFuncaoController.pas',
  UTelaCadastro in '..\Comum\Tela\UTelaCadastro.pas' {FTelaCadastro},
  UTela in '..\Comum\Tela\UTela.pas' {FTela},
  ULookup in '..\Comum\Tela\ULookup.pas' {FLookup},
  UBase in '..\Comum\Tela\UBase.pas' {FBase},
  UDataModule in '..\Comum\Tela\UDataModule.pas' {FDataModule: TDataModule},
  UFiltro in '..\Comum\Tela\UFiltro.pas' {FFiltro},
  ULogin in '..\Comum\Tela\ULogin.pas' {FLogin},
  UMenu in 'Tela\UMenu.pas' {FMenu},
  Atributos in '..\..\Comum\Atributos.pas',
  Biblioteca in '..\..\Comum\Biblioteca.pas',
  Constantes in '..\..\Comum\Constantes.pas',
  FuncaoVO in '..\..\Comum\VO\FuncaoVO.pas',
  JSonVO in '..\..\Comum\VO\JSonVO.pas',
  UsuarioVO in '..\..\Comum\VO\UsuarioVO.pas',
  PapelVO in '..\..\Comum\VO\PapelVO.pas',
  PapelFuncaoVO in '..\..\Comum\VO\PapelFuncaoVO.pas',
  PlanoCentroResultadoVO in '..\..\Comum\VO\PlanoCentroResultadoVO.pas',
  CentroResultadoVO in '..\..\Comum\VO\CentroResultadoVO.pas',
  PlanoNaturezaFinanceiraVO in '..\..\Comum\VO\PlanoNaturezaFinanceiraVO.pas',
  ContabilContaController in '..\Cadastros Base\Controller\ContabilContaController.pas',
  ContabilContaVO in '..\..\Comum\VO\ContabilContaVO.pas',
  EnderecoVO in '..\..\Comum\VO\EnderecoVO.pas',
  ContatoVO in '..\..\Comum\VO\ContatoVO.pas',
  PessoaFisicaVO in '..\..\Comum\VO\PessoaFisicaVO.pas',
  PessoaJuridicaVO in '..\..\Comum\VO\PessoaJuridicaVO.pas',
  PessoaController in '..\Cadastros Base\Controller\PessoaController.pas',
  NaturezaFinanceiraVO in '..\..\Comum\VO\NaturezaFinanceiraVO.pas',
  PessoaVO in '..\..\Comum\VO\PessoaVO.pas',
  VendedorVO in '..\..\Comum\VO\VendedorVO.pas',
  ColaboradorVO in '..\..\Comum\VO\ColaboradorVO.pas',
  SetorVO in '..\..\Comum\VO\SetorVO.pas',
  EmpresaVO in '..\..\Comum\VO\EmpresaVO.pas',
  UfVO in '..\..\Comum\VO\UfVO.pas',
  PaisVO in '..\..\Comum\VO\PaisVO.pas',
  ContadorVO in '..\..\Comum\VO\ContadorVO.pas',
  FpasVO in '..\..\Comum\VO\FpasVO.pas',
  SindicatoVO in '..\..\Comum\VO\SindicatoVO.pas',
  CargoVO in '..\..\Comum\VO\CargoVO.pas',
  NivelFormacaoVO in '..\..\Comum\VO\NivelFormacaoVO.pas',
  TipoColaboradorVO in '..\..\Comum\VO\TipoColaboradorVO.pas',
  SituacaoForCliVO in '..\..\Comum\VO\SituacaoForCliVO.pas',
  AtividadeForCliVO in '..\..\Comum\VO\AtividadeForCliVO.pas',
  TributOperacaoFiscalVO in '..\..\Comum\VO\TributOperacaoFiscalVO.pas',
  TransportadoraVO in '..\..\Comum\VO\TransportadoraVO.pas',
  TipoNotaFiscalVO in '..\..\Comum\VO\TipoNotaFiscalVO.pas',
  SituacaoColaboradorVO in '..\..\Comum\VO\SituacaoColaboradorVO.pas',
  TipoAdmissaoVO in '..\..\Comum\VO\TipoAdmissaoVO.pas',
  UPlanoCentroResultado in 'Tela\UPlanoCentroResultado.pas' {FPlanoCentroResultado},
  UPlanoNaturezaFinanceira in 'Tela\UPlanoNaturezaFinanceira.pas' {FPlanoNaturezaFinanceira},
  PlanoCentroResultadoController in 'Controller\PlanoCentroResultadoController.pas',
  PlanoNaturezaFinanceiraController in 'Controller\PlanoNaturezaFinanceiraController.pas',
  FinDocumentoOrigemController in 'Controller\FinDocumentoOrigemController.pas',
  UFinDocumentoOrigem in 'Tela\UFinDocumentoOrigem.pas' {FFinDocumentoOrigem},
  FinTipoRecebimentoController in 'Controller\FinTipoRecebimentoController.pas',
  FinTipoRecebimentoVO in '..\..\Comum\VO\FinTipoRecebimentoVO.pas',
  UNaturezaFinanceira in 'Tela\UNaturezaFinanceira.pas' {FNaturezaFinanceira},
  UCentroResultado in 'Tela\UCentroResultado.pas' {FCentroResultado},
  NaturezaFinanceiraController in 'Controller\NaturezaFinanceiraController.pas',
  CentroResultadoController in 'Controller\CentroResultadoController.pas',
  ViewSessaoEmpresaController in '..\Comum\Controller\ViewSessaoEmpresaController.pas',
  AdministrativoFormularioVO in '..\..\Comum\VO\AdministrativoFormularioVO.pas',
  ViewSessaoEmpresaVO in '..\..\Comum\VO\ViewSessaoEmpresaVO.pas',
  UFinTipoRecebimento in 'Tela\UFinTipoRecebimento.pas' {FFinTipoRecebimento},
  UFinStatusParcela in 'Tela\UFinStatusParcela.pas' {FFinStatusParcela},
  FinStatusParcelaController in 'Controller\FinStatusParcelaController.pas',
  UFinLancamentoReceber in 'Tela\UFinLancamentoReceber.pas' {FFinLancamentoReceber},
  UFinParcelaRecebimento in 'Tela\UFinParcelaRecebimento.pas' {FFinParcelaRecebimento},
  FinLancamentoReceberController in 'Controller\FinLancamentoReceberController.pas',
  FinParcelaReceberController in 'Controller\FinParcelaReceberController.pas',
  FinParcelaRecebimentoController in 'Controller\FinParcelaRecebimentoController.pas',
  USelecionaCheque in 'Tela\USelecionaCheque.pas' {FSelecionaCheque},
  EmpresaSessaoVO in '..\..\Comum\VO\EmpresaSessaoVO.pas',
  EmpresaController in '..\Comum\Controller\EmpresaController.pas',
  FinDocumentoOrigemVO in '..\..\Comum\VO\FinDocumentoOrigemVO.pas',
  FinStatusParcelaVO in '..\..\Comum\VO\FinStatusParcelaVO.pas',
  FinLancamentoReceberVO in '..\..\Comum\VO\FinLancamentoReceberVO.pas',
  FinParcelaReceberVO in '..\..\Comum\VO\FinParcelaReceberVO.pas',
  FinParcelaRecebimentoVO in '..\..\Comum\VO\FinParcelaRecebimentoVO.pas',
  ViewFinLancamentoReceberVO in '..\..\Comum\VO\ViewFinLancamentoReceberVO.pas',
  ViewFinLancamentoReceberController in 'Controller\ViewFinLancamentoReceberController.pas',
  ContaCaixaVO in '..\..\Comum\VO\ContaCaixaVO.pas',
  FinLctoReceberNtFinanceiraVO in '..\..\Comum\VO\FinLctoReceberNtFinanceiraVO.pas',
  AgenciaBancoVO in '..\..\Comum\VO\AgenciaBancoVO.pas',
  BancoVO in '..\..\Comum\VO\BancoVO.pas',
  ContaCaixaController in '..\Cadastros Base\Controller\ContaCaixaController.pas',
  ClienteController in 'Controller\ClienteController.pas',
  ClienteVO in '..\..\Comum\VO\ClienteVO.pas',
  FinChequeRecebidoVO in '..\..\Comum\VO\FinChequeRecebidoVO.pas',
  ClientePessoaVO in '..\..\Comum\VO\ClientePessoaVO.pas',
  FinConfiguracaoBoletoController in 'Controller\FinConfiguracaoBoletoController.pas',
  FinConfiguracaoBoletoVO in '..\..\Comum\VO\FinConfiguracaoBoletoVO.pas',
  UFinConfiguracaoBoleto in 'Tela\UFinConfiguracaoBoleto.pas' {FFinConfiguracaoBoleto},
  UProcessaRetorno in 'Tela\UProcessaRetorno.pas' {FProcessaRetorno},
  PessoaFisicaJuridicaVO in '..\..\Comum\VO\PessoaFisicaJuridicaVO.pas',
  ColaboradorPessoaVO in '..\..\Comum\VO\ColaboradorPessoaVO.pas',
  CfopVO in '..\..\Comum\VO\CfopVO.pas',
  PlanoContaVO in '..\..\Comum\VO\PlanoContaVO.pas',
  PlanoContaRefSpedVO in '..\..\Comum\VO\PlanoContaRefSpedVO.pas',
  AdmParametroVO in '..\..\Comum\VO\AdmParametroVO.pas',
  AdmParametroController in '..\Comum\Controller\AdmParametroController.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'T2Ti ERP Contas a Receber';
  Application.CreateForm(TFMenu, FMenu);
  Application.CreateForm(TFDataModule, FDataModule);
  Application.Run;
end.
