kylix_bin=/opt/kylix3/bin
#kylix_bin=/home/toni/kylix3/bin
drivers_path=../../drivers/linux

install:
	cp ../../repman/repmand .
	cp ../../repman/utils/metaprint/metaprint .
	cp ../../repman/utils/metaview/metaview .
	cp ../../repman/utils/printrep/printrep .
	cp ../../repman/utils/reptotxt/reptotxt .
	cp ../../repman/utils/txttorep/txttorep .
	cp ../../repman/utils/startup/startup.bin repmand.bin
	cp repmand.bin metaview.bin
	cp repmand.bin printrep.bin
	cp printrep.bin printreptopdf.bin
	cp printrep.bin reportserverapp.bin
	cp printrep.bin reportservercon.bin
	cp printrep.bin repserverconfig.bin
	cp printrep.bin metaprint.bin
	cp printrep.bin repwebexe.bin
	cp ../../server/app/reportserverapp .
	cp ../../server/app/reportservercon .
	cp ../../server/config/repserverconfig .
	cp ../../server/web/repwebexe .
	cp ../../repman/utils/printreptopdf/printreptopdf .
	cp ../../repman/reportmanres.es .
	cp ../../repman/reportmanres.en .
	cp ../../LICENSE.TXT .
	tar c LICENSE.TXT reportmanres.en reportmanres.es repmand reportserverapp reportserverapp.sh reportservercon reportservercon.sh repserverconfig repserverconfig.sh metaprint metaview metaview.sh printrep printreptopdf printreptopdf.sh reptotxt txttorep repmand repmand.sh repmand.bin metaview.bin printrep.bin printreptopdf.bin metaprint.bin reportserverapp.bin reportservercon.bin repserverconfig.bin repwebexe repwebexe.bin README  > repmand-1_4p.i386.tar
	gzip repmand-1_4p.i386.tar
clean:
	-rm -f *.so *.so.1 *.so.2 *.so.1.0
	-rm -f repmand
	-rm -f dbxconnections dbxdrivers metaprint metaview printrep printreptopdf
	-rm -f reptotxt txttorep repserverconfig reportservercon repwebexe
	-rm -f *.gz
	-rm -f *.rep
	-rm -f *.cds
	-rm -Rf doc
	-rm -f *.rpmf
	-rm -f *.tar
	-rm -f *.pdf
	-rm -f qt_*
	-rm -f repmand.es
	-rm -f reportmanres*
	-rm -f LICENSE.TXT
	-rm -f dbxres.en.*
	-rm -f reportserverapp
	-rm -f *.bin
