program T2TiERPEstoque;

uses
  Forms,
  Constantes in '..\..\Comum\Constantes.pas',
  Atributos in '..\..\Comum\Atributos.pas',
  Biblioteca in '..\..\Comum\Biblioteca.pas',
  FuncaoVO in '..\..\Comum\VO\FuncaoVO.pas',
  JSonVO in '..\..\Comum\VO\JSonVO.pas',
  PapelFuncaoVO in '..\..\Comum\VO\PapelFuncaoVO.pas',
  PapelVO in '..\..\Comum\VO\PapelVO.pas',
  Tipos in '..\Comum\Tipos.pas',
  Conversor in '..\Comum\Conversor.pas',
  NotificationService in '..\Comum\NotificationService.pas',
  SessaoUsuario in '..\Comum\SessaoUsuario.pas',
  ColaboradorController in '..\Comum\Controller\ColaboradorController.pas',
  Controller in '..\Comum\Controller\Controller.pas',
  FuncaoController in '..\Comum\Controller\FuncaoController.pas',
  PapelController in '..\Comum\Controller\PapelController.pas',
  PapelFuncaoController in '..\Comum\Controller\PapelFuncaoController.pas',
  UsuarioController in '..\Comum\Controller\UsuarioController.pas',
  UBase in '..\Comum\Tela\UBase.pas' {FBase},
  UDataModule in '..\Comum\Tela\UDataModule.pas' {FDataModule: TDataModule},
  UFiltro in '..\Comum\Tela\UFiltro.pas' {FFiltro},
  ULogin in '..\Comum\Tela\ULogin.pas' {FLogin},
  ULookup in '..\Comum\Tela\ULookup.pas' {FLookup},
  UTela in '..\Comum\Tela\UTela.pas' {FTela},
  UTelaCadastro in '..\Comum\Tela\UTelaCadastro.pas' {FTelaCadastro},
  UMenu in 'Tela\UMenu.pas' {FMenu},
  UsuarioVO in '..\..\Comum\VO\UsuarioVO.pas',
  UEntradaNF in 'Tela\UEntradaNF.pas' {FEntradaNF},
  URequisicaoInterna in 'Tela\URequisicaoInterna.pas' {FRequisicaoInterna},
  RequisicaoInternaDetalheVO in '..\..\Comum\VO\RequisicaoInternaDetalheVO.pas',
  RequisicaoInternaCabecalhoVO in '..\..\Comum\VO\RequisicaoInternaCabecalhoVO.pas',
  UContagemEstoque in 'Tela\UContagemEstoque.pas' {FContagemEstoque},
  UHistoricoReajuste in 'Tela\UHistoricoReajuste.pas' {FHistoricoReajuste},
  UFormacaoPreco in 'Tela\UFormacaoPreco.pas' {FFormacaoPreco},
  AtividadeForCliVO in '..\..\Comum\VO\AtividadeForCliVO.pas',
  CargoVO in '..\..\Comum\VO\CargoVO.pas',
  CepVO in '..\..\Comum\VO\CepVO.pas',
  ColaboradorVO in '..\..\Comum\VO\ColaboradorVO.pas',
  ContabilContaVO in '..\..\Comum\VO\ContabilContaVO.pas',
  ContaCaixaVO in '..\..\Comum\VO\ContaCaixaVO.pas',
  ContadorVO in '..\..\Comum\VO\ContadorVO.pas',
  ContatoVO in '..\..\Comum\VO\ContatoVO.pas',
  EmpresaVO in '..\..\Comum\VO\EmpresaVO.pas',
  EnderecoVO in '..\..\Comum\VO\EnderecoVO.pas',
  FpasVO in '..\..\Comum\VO\FpasVO.pas',
  PaisVO in '..\..\Comum\VO\PaisVO.pas',
  PessoaFisicaVO in '..\..\Comum\VO\PessoaFisicaVO.pas',
  PessoaJuridicaVO in '..\..\Comum\VO\PessoaJuridicaVO.pas',
  PessoaVO in '..\..\Comum\VO\PessoaVO.pas',
  SetorVO in '..\..\Comum\VO\SetorVO.pas',
  SindicatoVO in '..\..\Comum\VO\SindicatoVO.pas',
  SituacaoColaboradorVO in '..\..\Comum\VO\SituacaoColaboradorVO.pas',
  SituacaoForCliVO in '..\..\Comum\VO\SituacaoForCliVO.pas',
  TipoAdmissaoVO in '..\..\Comum\VO\TipoAdmissaoVO.pas',
  TipoColaboradorVO in '..\..\Comum\VO\TipoColaboradorVO.pas',
  UfVO in '..\..\Comum\VO\UfVO.pas',
  ProdutoVO in '..\..\Comum\VO\ProdutoVO.pas',
  UnidadeProdutoVO in '..\..\Comum\VO\UnidadeProdutoVO.pas',
  TributGrupoTributarioVO in '..\..\Comum\VO\TributGrupoTributarioVO.pas',
  AlmoxarifadoVO in '..\..\Comum\VO\AlmoxarifadoVO.pas',
  AgenciaBancoVO in '..\..\Comum\VO\AgenciaBancoVO.pas',
  BancoVO in '..\..\Comum\VO\BancoVO.pas',
  EmpresaController in '..\Comum\Controller\EmpresaController.pas',
  ViewSessaoEmpresaController in '..\Comum\Controller\ViewSessaoEmpresaController.pas',
  AdministrativoFormularioVO in '..\..\Comum\VO\AdministrativoFormularioVO.pas',
  EmpresaSessaoVO in '..\..\Comum\VO\EmpresaSessaoVO.pas',
  ViewSessaoEmpresaVO in '..\..\Comum\VO\ViewSessaoEmpresaVO.pas',
  EstoqueContagemCabecalhoController in 'Controller\EstoqueContagemCabecalhoController.pas',
  EstoqueReajusteCabecalhoController in 'Controller\EstoqueReajusteCabecalhoController.pas',
  NfeDetalheController in 'Controller\NfeDetalheController.pas',
  RequisicaoInternaCabecalhoController in 'Controller\RequisicaoInternaCabecalhoController.pas',
  EstoqueReajusteDetalheVO in '..\..\Comum\VO\EstoqueReajusteDetalheVO.pas',
  EstoqueContagemCabecalhoVO in '..\..\Comum\VO\EstoqueContagemCabecalhoVO.pas',
  EstoqueContagemDetalheVO in '..\..\Comum\VO\EstoqueContagemDetalheVO.pas',
  EstoqueReajusteCabecalhoVO in '..\..\Comum\VO\EstoqueReajusteCabecalhoVO.pas',
  ProdutoMarcaVO in '..\..\Comum\VO\ProdutoMarcaVO.pas',
  ProdutoSubGrupoVO in '..\..\Comum\VO\ProdutoSubGrupoVO.pas',
  ProdutoGrupoVO in '..\..\Comum\VO\ProdutoGrupoVO.pas',
  ProdutoLoteVO in '..\..\Comum\VO\ProdutoLoteVO.pas',
  ProdutoLacreVO in '..\..\Comum\VO\ProdutoLacreVO.pas',
  ColaboradorPessoaVO in '..\..\Comum\VO\ColaboradorPessoaVO.pas',
  PessoaFisicaJuridicaVO in '..\..\Comum\VO\PessoaFisicaJuridicaVO.pas',
  RequisicaoInternaDetalheController in 'Controller\RequisicaoInternaDetalheController.pas',
  UDataModuleNFe in '..\Comum\Tela\UDataModuleNFe.pas' {FDataModuleNFe: TDataModule},
  NfeTransporteVolumeVO in '..\..\Comum\VO\NfeTransporteVolumeVO.pas',
  NfeCabecalhoVO in '..\..\Comum\VO\NfeCabecalhoVO.pas',
  NfeCanaDeducoesSafraVO in '..\..\Comum\VO\NfeCanaDeducoesSafraVO.pas',
  NfeCanaFornecimentoDiarioVO in '..\..\Comum\VO\NfeCanaFornecimentoDiarioVO.pas',
  NfeCanaVO in '..\..\Comum\VO\NfeCanaVO.pas',
  NfeCteReferenciadoVO in '..\..\Comum\VO\NfeCteReferenciadoVO.pas',
  NfeCupomFiscalReferenciadoVO in '..\..\Comum\VO\NfeCupomFiscalReferenciadoVO.pas',
  NfeDeclaracaoImportacaoVO in '..\..\Comum\VO\NfeDeclaracaoImportacaoVO.pas',
  NfeDeducoesSafraVO in '..\..\Comum\VO\NfeDeducoesSafraVO.pas',
  NfeDestinatarioVO in '..\..\Comum\VO\NfeDestinatarioVO.pas',
  NfeDetalheImpostoCofinsVO in '..\..\Comum\VO\NfeDetalheImpostoCofinsVO.pas',
  NfeDetalheImpostoIcmsVO in '..\..\Comum\VO\NfeDetalheImpostoIcmsVO.pas',
  NfeDetalheImpostoIiVO in '..\..\Comum\VO\NfeDetalheImpostoIiVO.pas',
  NfeDetalheImpostoIpiVO in '..\..\Comum\VO\NfeDetalheImpostoIpiVO.pas',
  NfeDetalheImpostoIssqnVO in '..\..\Comum\VO\NfeDetalheImpostoIssqnVO.pas',
  NfeDetalheImpostoPisVO in '..\..\Comum\VO\NfeDetalheImpostoPisVO.pas',
  NfeDetalheVO in '..\..\Comum\VO\NfeDetalheVO.pas',
  NfeDetEspecificoArmamentoVO in '..\..\Comum\VO\NfeDetEspecificoArmamentoVO.pas',
  NfeDetEspecificoCombustivelVO in '..\..\Comum\VO\NfeDetEspecificoCombustivelVO.pas',
  NfeDetEspecificoMedicamentoVO in '..\..\Comum\VO\NfeDetEspecificoMedicamentoVO.pas',
  NfeDetEspecificoVeiculoVO in '..\..\Comum\VO\NfeDetEspecificoVeiculoVO.pas',
  NfeDuplicataVO in '..\..\Comum\VO\NfeDuplicataVO.pas',
  NfeEmitenteVO in '..\..\Comum\VO\NfeEmitenteVO.pas',
  NfeFaturaVO in '..\..\Comum\VO\NfeFaturaVO.pas',
  NfeImportacaoDetalheVO in '..\..\Comum\VO\NfeImportacaoDetalheVO.pas',
  NfeLocalEntregaVO in '..\..\Comum\VO\NfeLocalEntregaVO.pas',
  NfeLocalRetiradaVO in '..\..\Comum\VO\NfeLocalRetiradaVO.pas',
  NfeNfReferenciadaVO in '..\..\Comum\VO\NfeNfReferenciadaVO.pas',
  NfeNumeroVO in '..\..\Comum\VO\NfeNumeroVO.pas',
  NfeProcessoReferenciadoVO in '..\..\Comum\VO\NfeProcessoReferenciadoVO.pas',
  NfeProdRuralReferenciadaVO in '..\..\Comum\VO\NfeProdRuralReferenciadaVO.pas',
  NfeReferenciadaVO in '..\..\Comum\VO\NfeReferenciadaVO.pas',
  NfeTransporteReboqueVO in '..\..\Comum\VO\NfeTransporteReboqueVO.pas',
  NfeTransporteVO in '..\..\Comum\VO\NfeTransporteVO.pas',
  NfeTransporteVolumeLacreVO in '..\..\Comum\VO\NfeTransporteVolumeLacreVO.pas',
  NivelFormacaoVO in '..\..\Comum\VO\NivelFormacaoVO.pas',
  NfeConfiguracaoController in 'Controller\NfeConfiguracaoController.pas',
  NfeConfiguracaoVO in '..\..\Comum\VO\NfeConfiguracaoVO.pas',
  TributIcmsCustomCabVO in '..\..\Comum\VO\TributIcmsCustomCabVO.pas',
  TributIcmsCustomDetVO in '..\..\Comum\VO\TributIcmsCustomDetVO.pas',
  ViewPessoaFornecedorController in 'Controller\ViewPessoaFornecedorController.pas',
  ViewPessoaFornecedorVO in '..\..\Comum\VO\ViewPessoaFornecedorVO.pas',
  ViewPessoaTransportadoraController in 'Controller\ViewPessoaTransportadoraController.pas',
  ViewPessoaTransportadoraVO in '..\..\Comum\VO\ViewPessoaTransportadoraVO.pas',
  UProduto in '..\Cadastros Base\Tela\UProduto.pas' {FProduto},
  UnidadeProdutoController in '..\Cadastros Base\Controller\UnidadeProdutoController.pas',
  ProdutoSubGrupoController in '..\Cadastros Base\Controller\ProdutoSubGrupoController.pas',
  ProdutoMarcaController in '..\Cadastros Base\Controller\ProdutoMarcaController.pas',
  AlmoxarifadoController in '..\Cadastros Base\Controller\AlmoxarifadoController.pas',
  TributGrupoTributarioController in '..\Cadastros Base\Controller\TributGrupoTributarioController.pas',
  NcmVO in '..\..\Comum\VO\NcmVO.pas',
  NcmController in '..\Cadastros Base\Controller\NcmController.pas',
  TributIcmsCustomCabController in '..\Cadastros Base\Controller\TributIcmsCustomCabController.pas',
  ProdutoController in '..\Cadastros Base\Controller\ProdutoController.pas',
  NfeDetEspecificoMedicamentoController in 'Controller\NfeDetEspecificoMedicamentoController.pas',
  NfeDeclaracaoImportacaoController in 'Controller\NfeDeclaracaoImportacaoController.pas',
  NfeDetEspecificoArmamentoController in 'Controller\NfeDetEspecificoArmamentoController.pas',
  UNfeDetalheAnexo in 'Tela\UNfeDetalheAnexo.pas' {FNfeDetalheAnexo},
  NfeCabecalhoController in 'Controller\NfeCabecalhoController.pas',
  TributOperacaoFiscalVO in '..\..\Comum\VO\TributOperacaoFiscalVO.pas',
  CfopVO in '..\..\Comum\VO\CfopVO.pas',
  FiscalNotaFiscalEntradaVO in '..\..\Comum\VO\FiscalNotaFiscalEntradaVO.pas',
  PlanoContaRefSpedVO in '..\..\Comum\VO\PlanoContaRefSpedVO.pas',
  PlanoContaVO in '..\..\Comum\VO\PlanoContaVO.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'T2Ti ERP Estoque';
  Application.CreateForm(TFMenu, FMenu);
  Application.CreateForm(TFDataModule, FDataModule);
  Application.CreateForm(TFDataModuleNFe, FDataModuleNFe);
  Application.Run;
end.
