program T2TiERPPatrimonio;

uses
  Forms,
  Constantes in '..\..\Comum\Constantes.pas',
  Atributos in '..\..\Comum\Atributos.pas',
  Biblioteca in '..\..\Comum\Biblioteca.pas',
  FuncaoVO in '..\..\Comum\VO\FuncaoVO.pas',
  JSonVO in '..\..\Comum\VO\JSonVO.pas',
  PapelFuncaoVO in '..\..\Comum\VO\PapelFuncaoVO.pas',
  PapelVO in '..\..\Comum\VO\PapelVO.pas',
  Conversor in '..\Comum\Conversor.pas',
  NotificationService in '..\Comum\NotificationService.pas',
  SessaoUsuario in '..\Comum\SessaoUsuario.pas',
  ColaboradorController in '..\Comum\Controller\ColaboradorController.pas',
  Controller in '..\Comum\Controller\Controller.pas',
  FuncaoController in '..\Comum\Controller\FuncaoController.pas',
  PapelController in '..\Comum\Controller\PapelController.pas',
  PapelFuncaoController in '..\Comum\Controller\PapelFuncaoController.pas',
  UsuarioController in '..\Comum\Controller\UsuarioController.pas',
  UBase in '..\Comum\Tela\UBase.pas' {FBase},
  UDataModule in '..\Comum\Tela\UDataModule.pas' {FDataModule: TDataModule},
  UFiltro in '..\Comum\Tela\UFiltro.pas' {FFiltro},
  ULogin in '..\Comum\Tela\ULogin.pas' {FLogin},
  ULookup in '..\Comum\Tela\ULookup.pas' {FLookup},
  UTela in '..\Comum\Tela\UTela.pas' {FTela},
  UTelaCadastro in '..\Comum\Tela\UTelaCadastro.pas' {FTelaCadastro},
  UMenu in 'Tela\UMenu.pas' {FMenu},
  UsuarioVO in '..\..\Comum\VO\UsuarioVO.pas',
  PatrimTaxaDepreciacaoController in 'Controller\PatrimTaxaDepreciacaoController.pas',
  PatrimIndiceAtualizacaoController in 'Controller\PatrimIndiceAtualizacaoController.pas',
  PatrimTaxaDepreciacaoVO in '..\..\Comum\VO\PatrimTaxaDepreciacaoVO.pas',
  PatrimIndiceAtualizacaoVO in '..\..\Comum\VO\PatrimIndiceAtualizacaoVO.pas',
  UPatrimIndiceAtualizacao in 'Tela\UPatrimIndiceAtualizacao.pas' {FPatrimIndiceAtualizacao},
  UPatrimTaxaDepreciacao in 'Tela\UPatrimTaxaDepreciacao.pas' {FPatrimTaxaDepreciacao},
  PatrimTipoAquisicaoBemController in 'Controller\PatrimTipoAquisicaoBemController.pas',
  PatrimTipoAquisicaoBemVO in '..\..\Comum\VO\PatrimTipoAquisicaoBemVO.pas',
  UPatrimTipoAquisicaoBem in 'Tela\UPatrimTipoAquisicaoBem.pas' {FPatrimTipoAquisicaoBem},
  UPatrimTipoMovimentacao in 'Tela\UPatrimTipoMovimentacao.pas' {FPatrimTipoMovimentacao},
  PatrimTipoMovimentacaoController in 'Controller\PatrimTipoMovimentacaoController.pas',
  PatrimTipoMovimentacaoVO in '..\..\Comum\VO\PatrimTipoMovimentacaoVO.pas',
  PatrimEstadoConservacaoVO in '..\..\Comum\VO\PatrimEstadoConservacaoVO.pas',
  PatrimEstadoConservacaoController in 'Controller\PatrimEstadoConservacaoController.pas',
  UPatrimEstadoConservacao in 'Tela\UPatrimEstadoConservacao.pas' {FPatrimEstadoConservacao},
  PatrimGrupoBemController in 'Controller\PatrimGrupoBemController.pas',
  PatrimGrupoBemVO in '..\..\Comum\VO\PatrimGrupoBemVO.pas',
  UPatrimGrupoBem in 'Tela\UPatrimGrupoBem.pas' {FPatrimGrupoBem},
  USeguradora in 'Tela\USeguradora.pas' {FSeguradora},
  SeguradoraVO in '..\..\Comum\VO\SeguradoraVO.pas',
  SeguradoraController in 'Controller\SeguradoraController.pas',
  PatrimApoliceSeguroController in 'Controller\PatrimApoliceSeguroController.pas',
  PatrimApoliceSeguroVO in '..\..\Comum\VO\PatrimApoliceSeguroVO.pas',
  UPatrimApoliceSeguro in 'Tela\UPatrimApoliceSeguro.pas' {FPatrimApoliceSeguro},
  PatrimBemController in 'Controller\PatrimBemController.pas',
  PatrimMovimentacaoBemVO in '..\..\Comum\VO\PatrimMovimentacaoBemVO.pas',
  PatrimBemVO in '..\..\Comum\VO\PatrimBemVO.pas',
  PatrimDepreciacaoBemVO in '..\..\Comum\VO\PatrimDepreciacaoBemVO.pas',
  PatrimDocumentoBemVO in '..\..\Comum\VO\PatrimDocumentoBemVO.pas',
  UPatrimBem in 'Tela\UPatrimBem.pas' {FPatrimBem},
  AtividadeForCliVO in '..\..\Comum\VO\AtividadeForCliVO.pas',
  CargoVO in '..\..\Comum\VO\CargoVO.pas',
  ColaboradorVO in '..\..\Comum\VO\ColaboradorVO.pas',
  ContabilContaVO in '..\..\Comum\VO\ContabilContaVO.pas',
  ContadorVO in '..\..\Comum\VO\ContadorVO.pas',
  ContatoVO in '..\..\Comum\VO\ContatoVO.pas',
  EmpresaVO in '..\..\Comum\VO\EmpresaVO.pas',
  EnderecoVO in '..\..\Comum\VO\EnderecoVO.pas',
  EstadoCivilVO in '..\..\Comum\VO\EstadoCivilVO.pas',
  FpasVO in '..\..\Comum\VO\FpasVO.pas',
  PaisVO in '..\..\Comum\VO\PaisVO.pas',
  PessoaFisicaVO in '..\..\Comum\VO\PessoaFisicaVO.pas',
  PessoaJuridicaVO in '..\..\Comum\VO\PessoaJuridicaVO.pas',
  PessoaVO in '..\..\Comum\VO\PessoaVO.pas',
  SetorVO in '..\..\Comum\VO\SetorVO.pas',
  SindicatoVO in '..\..\Comum\VO\SindicatoVO.pas',
  SituacaoColaboradorVO in '..\..\Comum\VO\SituacaoColaboradorVO.pas',
  SituacaoForCliVO in '..\..\Comum\VO\SituacaoForCliVO.pas',
  TipoAdmissaoVO in '..\..\Comum\VO\TipoAdmissaoVO.pas',
  TipoColaboradorVO in '..\..\Comum\VO\TipoColaboradorVO.pas',
  TipoRelacionamentoVO in '..\..\Comum\VO\TipoRelacionamentoVO.pas',
  UfVO in '..\..\Comum\VO\UfVO.pas',
  NivelFormacaoVO in '..\..\Comum\VO\NivelFormacaoVO.pas',
  AdministrativoFormularioVO in '..\..\Comum\VO\AdministrativoFormularioVO.pas',
  ContabilHistoricoVO in '..\..\Comum\VO\ContabilHistoricoVO.pas',
  ContabilContaController in 'Controller\ContabilContaController.pas',
  ContabilHistoricoController in 'Controller\ContabilHistoricoController.pas',
  FornecedorPessoaVO in '..\..\Comum\VO\FornecedorPessoaVO.pas',
  ColaboradorPessoaVO in '..\..\Comum\VO\ColaboradorPessoaVO.pas',
  Tipos in '..\Comum\Tipos.pas',
  FornecedorVO in '..\..\Comum\VO\FornecedorVO.pas',
  FornecedorController in 'Controller\FornecedorController.pas',
  SetorController in 'Controller\SetorController.pas',
  EmpresaSessaoVO in '..\..\Comum\VO\EmpresaSessaoVO.pas',
  ViewSessaoEmpresaVO in '..\..\Comum\VO\ViewSessaoEmpresaVO.pas',
  EmpresaController in '..\Comum\Controller\EmpresaController.pas',
  ViewSessaoEmpresaController in '..\Comum\Controller\ViewSessaoEmpresaController.pas',
  PessoaFisicaJuridicaVO in '..\..\Comum\VO\PessoaFisicaJuridicaVO.pas',
  PlanoContaRefSpedVO in '..\..\Comum\VO\PlanoContaRefSpedVO.pas',
  PlanoContaVO in '..\..\Comum\VO\PlanoContaVO.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TFMenu, FMenu);
  Application.CreateForm(TFDataModule, FDataModule);
  Application.Run;
end.
