program T2TiAdministrativo;

uses
  Forms,
  Classes,
  Windows,
  Dialogs,
  Tipos in '..\Comum\Tipos.pas',
  Conversor in '..\Comum\Conversor.pas',
  NotificationService in '..\Comum\NotificationService.pas',
  SessaoUsuario in '..\Comum\SessaoUsuario.pas',
  UsuarioController in '..\Comum\Controller\UsuarioController.pas',
  Controller in '..\Comum\Controller\Controller.pas',
  FuncaoController in '..\Comum\Controller\FuncaoController.pas',
  PapelController in '..\Comum\Controller\PapelController.pas',
  PapelFuncaoController in '..\Comum\Controller\PapelFuncaoController.pas',
  UTelaCadastro in '..\Comum\Tela\UTelaCadastro.pas' {FTelaCadastro},
  UTela in '..\Comum\Tela\UTela.pas' {FTela},
  ULookup in '..\Comum\Tela\ULookup.pas' {FLookup},
  UBase in '..\Comum\Tela\UBase.pas' {FBase},
  UDataModule in '..\Comum\Tela\UDataModule.pas' {FDataModule: TDataModule},
  UFiltro in '..\Comum\Tela\UFiltro.pas' {FFiltro},
  ULogin in '..\Comum\Tela\ULogin.pas' {FLogin},
  UMenu in 'Tela\UMenu.pas' {FMenu},
  Atributos in '..\..\Comum\Atributos.pas',
  Biblioteca in '..\..\Comum\Biblioteca.pas',
  Constantes in '..\..\Comum\Constantes.pas',
  FuncaoVO in '..\..\Comum\VO\FuncaoVO.pas',
  JSonVO in '..\..\Comum\VO\JSonVO.pas',
  UsuarioVO in '..\..\Comum\VO\UsuarioVO.pas',
  PapelVO in '..\..\Comum\VO\PapelVO.pas',
  PapelFuncaoVO in '..\..\Comum\VO\PapelFuncaoVO.pas',
  PessoaVO in '..\..\Comum\VO\PessoaVO.pas',
  EnderecoVO in '..\..\Comum\VO\EnderecoVO.pas',
  ContatoVO in '..\..\Comum\VO\ContatoVO.pas',
  PessoaFisicaVO in '..\..\Comum\VO\PessoaFisicaVO.pas',
  PessoaJuridicaVO in '..\..\Comum\VO\PessoaJuridicaVO.pas',
  ColaboradorVO in '..\..\Comum\VO\ColaboradorVO.pas',
  SetorVO in '..\..\Comum\VO\SetorVO.pas',
  CargoVO in '..\..\Comum\VO\CargoVO.pas',
  UfVO in '..\..\Comum\VO\UfVO.pas',
  PaisVO in '..\..\Comum\VO\PaisVO.pas',
  ContadorVO in '..\..\Comum\VO\ContadorVO.pas',
  FpasVO in '..\..\Comum\VO\FpasVO.pas',
  SindicatoVO in '..\..\Comum\VO\SindicatoVO.pas',
  NivelFormacaoVO in '..\..\Comum\VO\NivelFormacaoVO.pas',
  TipoColaboradorVO in '..\..\Comum\VO\TipoColaboradorVO.pas',
  ContabilContaVO in '..\..\Comum\VO\ContabilContaVO.pas',
  SituacaoColaboradorVO in '..\..\Comum\VO\SituacaoColaboradorVO.pas',
  TipoAdmissaoVO in '..\..\Comum\VO\TipoAdmissaoVO.pas',
  UUsuario in 'Tela\UUsuario.pas' {FUsuario},
  UPapel in 'Tela\UPapel.pas' {FPapel},
  ColaboradorController in 'Controller\ColaboradorController.pas',
  AdministrativoFormularioVO in '..\..\Comum\VO\AdministrativoFormularioVO.pas',
  UAuditoria in 'Tela\UAuditoria.pas' {FAuditoria},
  AuditoriaVO in '..\..\Comum\VO\AuditoriaVO.pas',
  AuditoriaController in 'Controller\AuditoriaController.pas',
  EmpresaSessaoVO in '..\..\Comum\VO\EmpresaSessaoVO.pas',
  EmpresaVO in '..\..\Comum\VO\EmpresaVO.pas',
  EmpresaController in '..\Comum\Controller\EmpresaController.pas',
  ViewSessaoEmpresaController in '..\Comum\Controller\ViewSessaoEmpresaController.pas',
  ViewSessaoEmpresaVO in '..\..\Comum\VO\ViewSessaoEmpresaVO.pas',
  UAtualizaExe in 'Tela\UAtualizaExe.pas' {FAtualizaExe},
  UTributOperacaoFiscal in 'Tela\UTributOperacaoFiscal.pas' {FTributOperacaoFiscal},
  TributOperacaoFiscalController in 'Controller\TributOperacaoFiscalController.pas',
  TributOperacaoFiscalVO in '..\..\Comum\VO\TributOperacaoFiscalVO.pas',
  CfopController in '..\Cadastros Base\Controller\CfopController.pas',
  CfopVO in '..\..\Comum\VO\CfopVO.pas',
  TributGrupoTributarioVO in '..\..\Comum\VO\TributGrupoTributarioVO.pas',
  TributGrupoTributarioController in 'Controller\TributGrupoTributarioController.pas',
  UTributGrupoTributario in 'Tela\UTributGrupoTributario.pas' {FTributGrupoTributario},
  UTributacao in 'Tela\UTributacao.pas' {FTributacao},
  TributConfiguraOfGtController in 'Controller\TributConfiguraOfGtController.pas',
  TributConfiguraOfGtVO in '..\..\Comum\VO\TributConfiguraOfGtVO.pas',
  TributPisCodApuracaoVO in '..\..\Comum\VO\TributPisCodApuracaoVO.pas',
  TributCofinsCodApuracaoVO in '..\..\Comum\VO\TributCofinsCodApuracaoVO.pas',
  TributIpiDipiVO in '..\..\Comum\VO\TributIpiDipiVO.pas',
  TributIcmsUfVO in '..\..\Comum\VO\TributIcmsUfVO.pas',
  CsosnBVO in '..\..\Comum\VO\CsosnBVO.pas',
  CstIcmsBVO in '..\..\Comum\VO\CstIcmsBVO.pas',
  CsosnBController in '..\Cadastros Base\Controller\CsosnBController.pas',
  CstIcmsBController in '..\Cadastros Base\Controller\CstIcmsBController.pas',
  CstPisController in '..\Cadastros Base\Controller\CstPisController.pas',
  CstPisVO in '..\..\Comum\VO\CstPisVO.pas',
  CstCofinsController in '..\Cadastros Base\Controller\CstCofinsController.pas',
  CstCofinsVO in '..\..\Comum\VO\CstCofinsVO.pas',
  CodigoApuracaoEfdController in '..\Cadastros Base\Controller\CodigoApuracaoEfdController.pas',
  CodigoApuracaoEfdVO in '..\..\Comum\VO\CodigoApuracaoEfdVO.pas',
  TipoReceitaDipiController in '..\Cadastros Base\Controller\TipoReceitaDipiController.pas',
  TipoReceitaDipiVO in '..\..\Comum\VO\TipoReceitaDipiVO.pas',
  UfController in '..\Cadastros Base\Controller\UfController.pas',
  CstIpiVO in '..\..\Comum\VO\CstIpiVO.pas',
  CstIpiController in '..\Cadastros Base\Controller\CstIpiController.pas',
  TributIcmsUfController in 'Controller\TributIcmsUfController.pas',
  UTributIcmsCustomizado in 'Tela\UTributIcmsCustomizado.pas' {FTributIcmsCustomizado},
  TributIcmsCustomDetController in 'Controller\TributIcmsCustomDetController.pas',
  TributIcmsCustomCabController in 'Controller\TributIcmsCustomCabController.pas',
  TributIcmsCustomDetVO in '..\..\Comum\VO\TributIcmsCustomDetVO.pas',
  TributIcmsCustomCabVO in '..\..\Comum\VO\TributIcmsCustomCabVO.pas',
  TributIssController in 'Controller\TributIssController.pas',
  TributIssVO in '..\..\Comum\VO\TributIssVO.pas',
  UTributIss in 'Tela\UTributIss.pas' {FTributIss},
  PlanoContaRefSpedVO in '..\..\Comum\VO\PlanoContaRefSpedVO.pas',
  PlanoContaVO in '..\..\Comum\VO\PlanoContaVO.pas',
  UParametrizacao in 'Tela\UParametrizacao.pas' {FParametrizacao},
  AdmParametroVO in '..\..\Comum\VO\AdmParametroVO.pas',
  AdmParametroController in '..\Comum\Controller\AdmParametroController.pas',
  FinStatusParcelaVO in '..\..\Comum\VO\FinStatusParcelaVO.pas',
  FinStatusParcelaController in 'Controller\FinStatusParcelaController.pas',
  FinTipoRecebimentoVO in '..\..\Comum\VO\FinTipoRecebimentoVO.pas',
  FinTipoRecebimentoController in 'Controller\FinTipoRecebimentoController.pas',
  FinDocumentoOrigemVO in '..\..\Comum\VO\FinDocumentoOrigemVO.pas',
  FinDocumentoOrigemController in 'Controller\FinDocumentoOrigemController.pas',
  ContaCaixaVO in '..\..\Comum\VO\ContaCaixaVO.pas',
  ContaCaixaController in 'Controller\ContaCaixaController.pas',
  AgenciaBancoVO in '..\..\Comum\VO\AgenciaBancoVO.pas',
  BancoVO in '..\..\Comum\VO\BancoVO.pas',
  UEmpresa in 'Tela\UEmpresa.pas' {FEmpresa},
  ContadorController in 'Controller\ContadorController.pas',
  SindicatoController in 'Controller\SindicatoController.pas',
  FpasController in 'Controller\FpasController.pas',
  EnderecoController in 'Controller\EnderecoController.pas',
  ContatoController in 'Controller\ContatoController.pas',
  UEmpresaCnae in 'Tela\UEmpresaCnae.pas' {FEmpresaCnae},
  EmpresaCnaeController in 'Controller\EmpresaCnaeController.pas',
  EmpresaCnaeVO in '..\..\Comum\VO\EmpresaCnaeVO.pas',
  CnaeController in 'Controller\CnaeController.pas',
  CnaeVO in '..\..\Comum\VO\CnaeVO.pas',
  UQuadroSocietario in 'Tela\UQuadroSocietario.pas' {FQuadroSocietario},
  QuadroSocietarioController in 'Controller\QuadroSocietarioController.pas',
  QuadroSocietarioVO in '..\..\Comum\VO\QuadroSocietarioVO.pas',
  USocio in 'Tela\USocio.pas' {FSocio},
  SocioDependenteVO in '..\..\Comum\VO\SocioDependenteVO.pas',
  SocioParticipacaoSocietariaVO in '..\..\Comum\VO\SocioParticipacaoSocietariaVO.pas',
  SocioVO in '..\..\Comum\VO\SocioVO.pas',
  SocioController in 'Controller\SocioController.pas',
  TipoRelacionamentoVO in '..\..\Comum\VO\TipoRelacionamentoVO.pas',
  PessoaController in 'Controller\PessoaController.pas',
  TipoRelacionamentoController in 'Controller\TipoRelacionamentoController.pas',
  UAtualizaBd in 'Tela\UAtualizaBd.pas' {FAtualizaBd};

{$R *.res}
{$R T2TiERP_Forms.RES}

begin
  Application.Initialize;
  Application.Title := 'T2Ti ERP Administrativo';
  Application.CreateForm(TFMenu, FMenu);
  Application.CreateForm(TFDataModule, FDataModule);
  Application.Run;
end.
