// Do not edit. This file is machine generated by the Resource DLL Wizard.

library repmandlinux;

{$R *.res}
{ITE} {LCID:00000409:00000C0A} {}
{ITE} {DFMFileType} {vcl/DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl/DBPWDLG.dfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpgdidriver.dfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rprfvparams.dfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpvpreview.dfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpdbxconfig.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpexpredlg.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpfparams.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpgraphutils.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpmdfabout.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpmdfdatainfo.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpmdfdesign.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpmdfgrid.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpmdfhelpform.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpmdfmain.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpmdfsampledata.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpmdfstruc.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpmdobjinsp.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rppagesetup.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rppreview.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpprintdia.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rpqtdriver.xfm}
{ITE} {DFMFileType} {c/prog/toni/cvsroot/reportman/reportman/rprfparams.xfm}
//{ITE} {RCFileType} {repmand_DRC.rc}

{$R 'vcl/DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl/DBPWDLG.dfm' PasswordDialog:TForm(Form)}
//{$R 'c/prog/toni/cvsroot/reportman/reportman/rpgdidriver.dfm' FRpVCLProgress:TForm}
//{$R 'c/prog/toni/cvsroot/reportman/reportman/rprfvparams.dfm' FRpRTParams:TForm}
//{$R 'c/prog/toni/cvsroot/reportman/reportman/rpvpreview.dfm' FRpVPreview:TForm}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rpdbxconfig.xfm' FRpDBXConfig:TForm}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rpexpredlg.xfm' FrpExpredialog:TForm}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rpfparams.xfm' FRpParams:TForm}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rpgraphutils.xfm' FRpGraphProgres:TForm}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rpmdfabout.xfm' FRpAboutBox:TForm}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rpmdfdatainfo.xfm' FRpDatainfoconfig:TForm}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rpmdfdesign.xfm' FRpDesignFrame:TFrame}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rpmdfgrid.xfm' FRpGridOptions:TForm}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rpmdfhelpform.xfm' FRpHelpForm:TForm}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rpmdfmain.xfm' FRpMainF:TForm}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rpmdfsampledata.xfm' FRpShowSampledata:TForm}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rpmdfstruc.xfm' FRpStructure:TFrame}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rpmdobjinsp.xfm' FRpObjInsp:TFrame}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rppagesetup.xfm' FRpPageSetup:TForm}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rppreview.xfm' FRpPreview:TForm}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rpprintdia.xfm' FRpPrintDialog:TForm}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rpqtdriver.xfm' FRpQtProgress:TForm}
{$R 'c/prog/toni/cvsroot/reportman/reportman/rprfparams.xfm' FRpRunTimeParams:TForm}
//{$R 'repmand_DRC.res' 'repmand_DRC.rc'}

{$E ESN}

begin
end.