; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Report Manager
AppVerName=Report Manager 2.9f
AppVersion=2.9f
OutputBaseFilename=repmandesigneronly2_9f
AppPublisher=Toni Martir
AppPublisherURL=http://reportman.sourceforge.net
AppSupportURL=http://sourceforge.net/projects/reportman
AppUpdatesURL=http://sourceforge.net/projects/reportman
DefaultDirName={pf}\Report Manager
DefaultGroupName=Report Manager
LicenseFile=license.txt
PrivilegesRequired=admin
LanguageDetectionMethod=uilanguage
WizardImageFile=HardwareClassic05.bmp
WizardImageStretch=False
WizardSmallImageFile=SetupModernSmall02.bmp
; uncomment the following line if you want your installation to run on NT 3.51 too.
; MinVersion=4,3.51

[Types]
Name: full; Description: {cm:Fullinstallation}
Name: custom; Description: {cm:Custominstallation}; Flags: iscustom

[Components]
Name: designer; Description: {cm:ReportManagerDesigner}; Types: full custom
Name: dbexpress; Description: {cm:DBExpressdatabasedrivers}; Types: full custom
;Name: help; Description: {cm:Documentation}; Types: full custom
Name: repsample; Description: {cm:ReportSamples}; Types: full custom

[Languages]
Name: en; MessagesFile: EnglishT.isl
Name: de; MessagesFile: GermanT.isl
Name: es; MessagesFile: SpanishT.isl
Name: cat; MessagesFile: CatalanT.isl
Name: pt; MessagesFile: PortugueseT.isl
Name: it; MessagesFile: ItalianT.isl
Name: fr; MessagesFile: FrenchT.isl

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: Additional icons:; MinVersion: 4,4
;Name: "quicklaunchicon"; Description: "Create a &Quick Launch icon"; GroupDescription: "Additional icons:"; MinVersion: 4,4; Flags: unchecked

[Files]
Source: ..\repman\repmandxp.exe; DestDir: {app}; Components: designer; Flags: ignoreversion
Source: ..\repman\repmandxp.ini; DestDir: {app}; Components: designer; Flags: ignoreversion
Source: ..\repman\repmandxp.exe.manifest; DestDir: {app}; Components: designer; Flags: ignoreversion
Source: ..\repman\reportmanres.*; DestDir: {app}; Flags: restartreplace
Source: ..\repman\transwin\repmandxp.*; DestDir: {app}; Components: designer; Flags: ignoreversion
Source: ..\repman\reportmanres.*; DestDir: {app}\net2; Flags: restartreplace
Source: license.txt; DestDir: {app}; Flags: ignoreversion
Source: ..\drivers\win32\upx.exe; DestDir: {app}; Flags: restartreplace

; Report Server custom files

Source: ..\repman\repsamples\sample4.rep; DestDir: {app}; Components: repsample; Flags: ignoreversion
Source: ..\repman\repsamples\biolife.cds; DestDir: {app}; Components: repsample; Flags: ignoreversion

Source: ..\repman\dbxdrivers.ini; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\repman\dbxconnections.ini; DestDir: {app}; Components: dbexpress; Flags: onlyifdoesntexist
Source: ..\drivers\win32new\dbxint.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxadapter.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxasa.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxase.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxdb2.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxinf.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxmss.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxmss9.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxmys.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxfb.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxora.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxoodbc.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion

; Api libraries
; Documentation
;Source: ..\doc\doc\*.*; DestDir: {app}\doc; Components: help; Flags: ignoreversion
;Source: ..\doc\doc\images\*.*; DestDir: {app}\doc\images; Components: help; Flags: ignoreversion
;Source: ..\doc\doc\units\*.*; DestDir: {app}\doc\units; Components: help; Flags: ignoreversion


[Registry]
Root: HKCR; Subkey: .rep; Components: designer; ValueType: string; ValueName: ; ValueData: Report Manager Designer; Flags: uninsdeletevalue
Root: HKCR; Subkey: Report Manager Designer; Components: designer; ValueType: string; ValueName: ; ValueData: Report Manager Designer File; Flags: uninsdeletekey
Root: HKCR; Subkey: Report Manager Designer\DefaultIcon; Components: designer; ValueType: string; ValueName: ; ValueData: {app}\repmandxp.exe,0
Root: HKCR; Subkey: Report Manager Designer\shell\open\command; Components: designer; ValueType: string; ValueName: ; ValueData: """{app}\repmandxp.exe"" ""%1"""


;DBExpress keys
Root: HKLM; Subkey: SOFTWARE\Borland\DBExpress; ValueType: string; Components: dbexpress; ValueName: Driver Registry File; ValueData: {app}\dbxdrivers.ini; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\DBExpress; ValueType: string; Components: dbexpress; ValueName: Connection Registry File; ValueData: {app}\dbxconnections.ini; Flags: createvalueifdoesntexist


[Icons]
Name: {group}\{cm:DesignerXP}; Filename: {app}\repmandxp.exe; Components: designer; WorkingDir: {app}
Name: {group}\{cm:SLicense}; Filename: {app}\license.txt
Name: {commondesktop}\{cm:ReportManagerDesignerXP}; Filename: {app}\repmandxp.exe; WorkingDir: {app}; Components: designer; MinVersion: 4,4; Tasks: desktopicon

[Run]
;For Windows Vista compatibilty it should not run Report Manager at end of installation
;Filename: {app}\repmandxp.exe; Description: {cm:LaunchReportManagerDesignerXP}; Components: designer; Flags: nowait postinstall skipifsilent
