; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Report Manager Standard Edition
AppVerName=Report Manager 2.9f
AppVersion=2.9f
OutputBaseFilename=reportmanstd2_9f
AppPublisher=Toni Martir
AppPublisherURL=http://reportman.sourceforge.net
AppSupportURL=http://sourceforge.net/projects/reportman
AppUpdatesURL=http://sourceforge.net/projects/reportman
DefaultDirName={pf}\Report Manager
DefaultGroupName=Report Manager
LicenseFile=license.txt
PrivilegesRequired=admin
LanguageDetectionMethod=uilanguage
WizardImageFile=HardwareClassic05.bmp
WizardImageStretch=False
WizardSmallImageFile=SetupModernSmall02.bmp
; uncomment the following line if you want your installation to run on NT 3.51 too.
; MinVersion=4,3.51

[Types]
Name: full; Description: {cm:Fullinstallation}
Name: custom; Description: {cm:Custominstallation}; Flags: iscustom

[Components]
Name: designer; Description: {cm:ReportManagerDesigner}; Types: full custom
Name: dbexpress; Description: {cm:DBExpressdatabasedrivers}; Types: full custom
Name: bde; Description: {cm:BorlandDatabaseEnginedatabasedrivers}; Types: full custom
Name: commandline; Description: {cm:Commandlinetools}; Types: full custom
Name: help; Description: {cm:Documentation}; Types: full custom
Name: servertcp; Description: {cm:TCPserver}; Types: full custom
Name: serverconf; Description: {cm:ServerconfigurationXP}; Types: full custom
Name: clienttcp; Description: {cm:TCPclientandmetafileviewer}; Types: full custom
Name: serverweb; Description: {cm:Webserver}; Types: full custom
Name: activex; Description: {cm:ActiveXcomponent}; Types: full custom
Name: ieplugin; Description: {cm:InternetExplorerplugin}; Types: full custom
Name: translation; Description: {cm:TranslationUtility}; Types: full custom
Name: repsample; Description: {cm:ReportSamples}; Types: full custom

[Languages]
Name: en; MessagesFile: EnglishT.isl
Name: de; MessagesFile: GermanT.isl
Name: es; MessagesFile: SpanishT.isl
Name: cat; MessagesFile: CatalanT.isl
Name: pt; MessagesFile: PortugueseT.isl
Name: it; MessagesFile: ItalianT.isl
Name: fr; MessagesFile: FrenchT.isl

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: Additional icons:; MinVersion: 4,4
;Name: "quicklaunchicon"; Description: "Create a &Quick Launch icon"; GroupDescription: "Additional icons:"; MinVersion: 4,4; Flags: unchecked

[Files]
Source: ..\repman\repmandxp.exe; DestDir: {app}; Components: designer; Flags: ignoreversion
Source: ..\repman\repmandxp.ini; DestDir: {app}; Components: designer; Flags: ignoreversion
Source: ..\repman\repmandxp.exe.manifest; DestDir: {app}; Components: designer; Flags: ignoreversion
Source: ..\repman\reportmanres.*; DestDir: {app}; Flags: restartreplace
Source: ..\repman\transwin\repmandxp.*; DestDir: {app}; Components: designer; Flags: ignoreversion
Source: ..\repman\transwin\metaviewxp.*; DestDir: {app}; Components: clienttcp; Flags: ignoreversion
Source: ..\repman\utils\metaview\metaviewxp.exe.manifest; DestDir: {app}; Components: clienttcp; Flags: ignoreversion
Source: ..\repman\utils\metaview\metaviewxp.exe; DestDir: {app}; Components: clienttcp; Flags: ignoreversion
Source: ..\repman\utils\metaprint\metaprintxp.exe; DestDir: {app}; Components: commandline; Flags: ignoreversion
Source: ..\repman\utils\metaprint\metaprintxp.exe.manifest; DestDir: {app}; Components: commandline; Flags: ignoreversion
Source: license.txt; DestDir: {app}; Flags: ignoreversion
Source: ..\repman\utils\printrep\printrepxp.exe; DestDir: {app}; Components: commandline; Flags: ignoreversion
Source: ..\repman\utils\printrep\printrepxp.exe.manifest; DestDir: {app}; Components: commandline; Flags: ignoreversion
Source: ..\repman\net\*.dll; DestDir: {app}\net; Components: commandline; Flags: ignoreversion
Source: ..\repman\net\*.exe; DestDir: {app}\net; Components: commandline; Flags: ignoreversion
Source: ..\repman\net2\printreport.exe; DestDir: {app}\net2; Components: commandline; Flags: ignoreversion
Source: ..\repman\net2\ICSharpCode.SharpZipLib.dll; DestDir: {app}\net2; Components: commandline; Flags: ignoreversion
Source: ..\repman\net2\Reportman.Drawing.dll; DestDir: {app}\net2; Components: commandline; Flags: ignoreversion
Source: ..\repman\net2\Reportman.Drawing.Forms.dll; DestDir: {app}\net2; Components: commandline; Flags: ignoreversion
Source: ..\repman\net2\Reportman.Reporting.dll; DestDir: {app}\net2; Components: commandline; Flags: ignoreversion
Source: ..\repman\net2\Reportman.Reporting.Forms.dll; DestDir: {app}\net2; Components: commandline; Flags: ignoreversion
Source: ..\repman\reportmanres.*; DestDir: {app}\net; Flags: restartreplace
Source: ..\repman\reportmanres.*; DestDir: {app}\net2; Flags: restartreplace
Source: ..\repman\utils\reptotxt\reptotxt.exe; DestDir: {app}; Components: commandline; Flags: ignoreversion
Source: ..\repman\utils\txttorep\txttorep.exe; DestDir: {app}; Components: commandline; Flags: ignoreversion
Source: ..\drivers\win32\upx.exe; DestDir: {sys}; Flags: restartreplace
Source: ..\repman\utils\rptranslator\rptranslate.exe; DestDir: {app}; Components: translation; Flags: ignoreversion
Source: ..\repman\utils\rptranslator\rptranslate.exe.manifest; DestDir: {app}; Components: translation; Flags: ignoreversion
Source: ..\repman\utils\rptranslator\rptranslateres.*; DestDir: {app}; Components: translation; Flags: ignoreversion
Source: ..\repman\utils\compilerep\compilerep.exe; DestDir: {app}; Components: commandline; Flags: ignoreversion
Source: ..\repman\utils\printreptopdf\printreptopdf.exe; DestDir: {app}; Components: commandline; Flags: ignoreversion
Source: ..\activex\ReportMan.ocx; DestDir: {sys}; Components: activex; Flags: restartreplace sharedfile regserver ignoreversion
Source: ..\activex\ReportMan.ocx.manifest; DestDir: {sys}; Components: activex
Source: ..\webactivex\WebReportManX.cab; DestDir: {app}; Components: ieplugin; Flags: ignoreversion
Source: ..\webactivex\WebReportManX.ocx; DestDir: {sys}; Components: ieplugin; Flags: restartreplace sharedfile regserver ignoreversion
Source: ..\server\service\repserverservice.exe; DestDir: {app}; Components: servertcp; Flags: ignoreversion
Source: ..\server\app\reportserverappxp.exe; DestDir: {app}; Components: servertcp; Flags: ignoreversion
Source: ..\server\app\reportserverappxp.exe.manifest; DestDir: {app}; Components: servertcp; Flags: ignoreversion
Source: ..\server\app\reportservercon.exe; DestDir: {app}; Components: servertcp; Flags: ignoreversion
Source: ..\server\config\repserverconfigxp.exe; DestDir: {app}; Components: serverconf; Flags: ignoreversion
Source: ..\server\config\repserverconfigxp.exe.manifest; DestDir: {app}; Components: serverconf; Flags: ignoreversion
Source: ..\server\service\repserviceinstall.exe; DestDir: {app}; Components: servertcp; Flags: ignoreversion
Source: ..\server\service\repserviceinstall.exe.manifest; DestDir: {app}; Components: servertcp; Flags: ignoreversion
Source: ..\server\web\repwebserver.dll; DestDir: {app}\webserver; Components: serverweb; Flags: ignoreversion
Source: ..\server\web\repwebexe.exe; DestDir: {app}\webserver; Components: serverweb; Flags: ignoreversion
; Report Server custom files
Source: ..\server\web\*.html; DestDir: {app}\webserver; Components: serverweb; Flags: ignoreversion
Source: ..\webactivex\reportman.htm; DestDir: {app}\sampleplugin; Components: ieplugin; Flags: ignoreversion

Source: ..\repman\repsamples\sample4.rep; DestDir: {app}; Components: repsample; Flags: ignoreversion
Source: ..\repman\repsamples\biolife.cds; DestDir: {app}; Components: repsample; Flags: ignoreversion

Source: ..\repman\dbxdrivers.ini; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\repman\dbxconnections.ini; DestDir: {app}; Components: dbexpress; Flags: onlyifdoesntexist
;Source: ..\drivers\win32\dbexpint.dll; DestDir: {sys}; Components: dbexpress; Flags: uninsneveruninstall restartreplace sharedfile
;Source: ..\drivers\win32\dbexpmys.dll; DestDir: {sys}; Components: dbexpress; Flags: uninsneveruninstall restartreplace sharedfile
;Source: ..\drivers\win32\dbexpinf.dll; DestDir: {sys}; Components: dbexpress; Flags: uninsneveruninstall restartreplace sharedfile
;Source: ..\drivers\win32\dbexpmysql.dll; DestDir: {sys}; Components: dbexpress; Flags: uninsneveruninstall restartreplace sharedfile
;Source: ..\drivers\win32\dbexpmss.dll; DestDir: {sys}; Components: dbexpress; Flags: uninsneveruninstall restartreplace sharedfile
;Source: ..\drivers\win32\dbexpora.dll; DestDir: {sys}; Components: dbexpress; Flags: uninsneveruninstall restartreplace sharedfile
;Source: ..\drivers\win32\dbexpdb2.dll; DestDir: {sys}; Components: dbexpress; Flags: uninsneveruninstall restartreplace sharedfile
;Source: ..\drivers\win32\dbxoodbc.dll; DestDir: {sys}; Components: dbexpress; Flags: uninsneveruninstall restartreplace sharedfile
Source: ..\drivers\win32new\dbxint.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxadapter.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxasa.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxase.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxdb2.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxinf.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxmss.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxmss9.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxmys.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxfb.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxora.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion
Source: ..\drivers\win32new\dbxoodbc.dll; DestDir: {app}; Components: dbexpress; Flags: ignoreversion

;BDE
Source: C:\Legacy\BDE\*.*; DestDir: {cf}\Borland Shared\BDE; Components: bde; Flags: uninsneveruninstall restartreplace sharedfile
Source: C:\Windows\System32\bdeadmin.cpl; DestDir: {sys}; Components: bde; Flags: uninsneveruninstall restartreplace sharedfile

; Api libraries
Source: ..\rpreportman.h; DestDir: {app}\api; Components: activex; Flags: ignoreversion
Source: ..\rpreportmanapi.bas; DestDir: {app}\api; Components: activex; Flags: ignoreversion
Source: ..\tests\gcctest\Reportman.def; DestDir: {app}\api; Components: activex; Flags: ignoreversion
; Documentation
Source: ..\doc\doc\*.*; DestDir: {app}\doc; Components: help; Flags: ignoreversion
Source: ..\doc\doc\images\*.*; DestDir: {app}\doc\images; Components: help; Flags: ignoreversion
Source: ..\doc\doc\units\*.*; DestDir: {app}\doc\units; Components: help; Flags: ignoreversion


[Registry]
Root: HKCR; Subkey: .rep; Components: designer; ValueType: string; ValueName: ; ValueData: Report Manager Designer; Flags: uninsdeletevalue
Root: HKCR; Subkey: Report Manager Designer; Components: designer; ValueType: string; ValueName: ; ValueData: Report Manager Designer File; Flags: uninsdeletekey
Root: HKCR; Subkey: Report Manager Designer\DefaultIcon; Components: designer; ValueType: string; ValueName: ; ValueData: {app}\repmandxp.exe,0
Root: HKCR; Subkey: Report Manager Designer\shell\open\command; Components: designer; ValueType: string; ValueName: ; ValueData: """{app}\repmandxp.exe"" ""%1"""

Root: HKCR; Subkey: .rpmf; Components: clienttcp; ValueType: string; ValueName: ; ValueData: Report Manager Client; Flags: uninsdeletevalue
Root: HKCR; Subkey: Report Manager Client; Components: clienttcp; ValueType: string; ValueName: ; ValueData: Report Manager Metafile; Flags: uninsdeletekey
Root: HKCR; Subkey: Report Manager Client\DefaultIcon; Components: clienttcp; ValueType: string; ValueName: ; ValueData: {app}\metaviewxp.exe,0
Root: HKCR; Subkey: Report Manager Client\shell\open\command; Components: clienttcp; ValueType: string; ValueName: ; ValueData: """{app}\metaviewxp.exe"" ""%1"""

;DBExpress keys
Root: HKLM; Subkey: SOFTWARE\Borland\DBExpress; ValueType: string; Components: dbexpress; ValueName: Driver Registry File; ValueData: {app}\dbxdrivers.ini; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\DBExpress; ValueType: string; Components: dbexpress; ValueName: Connection Registry File; ValueData: {app}\dbxconnections.ini; Flags: createvalueifdoesntexist

;BDE Registry
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine; ValueType: string; Components: bde; ValueName: DLLPATH; ValueData: {cf}\Borland Shared\BDE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine; ValueType: string; Components: bde; ValueName: CONFIGFILE01; ValueData: {cf}\Borland Shared\BDE\IDAPI.CFG; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine; ValueType: string; Components: bde; ValueName: RESOURCE; ValueData: 0009; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine; ValueType: string; Components: bde; ValueName: SaveConfig; ValueData: WIN32; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine; ValueType: string; Components: bde; ValueName: UseCount; ValueData: 7; Flags: createvalueifdoesntexist

;BDE DB2
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: USER NAME; ValueData: MYNAME; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: DB2 DSN; ValueData: DB2_SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: OPEN MODE; ValueData: READ/WRITE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE SIZE; ValueData: 8; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: LANGDRIVER; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: SQLQRYMODE; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: SQLPASSTHRU MODE; ValueData: SHARED AUTOCOMMIT; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE TIME; ValueData: -1; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: MAXROWS; ValueData: -1; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: BATCH COUNT; ValueData: 200; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: ENABLE SCHEMA CACHE; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE DIR; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: ENABLE BCD; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: ROWSET SIZE; ValueData: 20; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: BLOBS TO CACHE; ValueData: 64; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\DB OPEN; ValueType: string; Components: bde; ValueName: BLOB SIZE; ValueData: 32; Flags: createvalueifdoesntexist

;DB2 INIT
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\INIT; ValueType: string; Components: bde; ValueName: VERSION; ValueData: 4.0; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\INIT; ValueType: string; Components: bde; ValueName: TYPE; ValueData: SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\INIT; ValueType: string; Components: bde; ValueName: DLL32; ValueData: SQLDB2V5.DLL; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\INIT; ValueType: string; Components: bde; ValueName: DRIVER; ValueData: IBM DB2 DRIVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\INIT; ValueType: string; Components: bde; ValueName: DRIVER FLAGS; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DB2\INIT; ValueType: string; Components: bde; ValueName: TRACE MODE; ValueData: 0; Flags: createvalueifdoesntexist

;DBase INIT
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DBASE\INIT; ValueType: string; Components: bde; ValueName: VERSION; ValueData: 4.0; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DBASE\INIT; ValueType: string; Components: bde; ValueName: TYPE; ValueData: FILE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DBASE\INIT; ValueType: string; Components: bde; ValueName: LANGDRIVER; ValueData: DBWINES0; Flags: createvalueifdoesntexist

;DBase table create
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DBASE\TABLE CREATE; ValueType: string; Components: bde; ValueName: LEVEL; ValueData: 7; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DBASE\TABLE CREATE; ValueType: string; Components: bde; ValueName: MDX BLOCK SIZE; ValueData: 1024; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DBASE\TABLE CREATE; ValueType: string; Components: bde; ValueName: MEMO FILE BLOCK SIZE; ValueData: 1024; Flags: createvalueifdoesntexist

;Foxpro INIT
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\FOXPRO\INIT; ValueType: string; Components: bde; ValueName: VERSION; ValueData: 4.0; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\FOXPRO\INIT; ValueType: string; Components: bde; ValueName: TYPE; ValueData: FILE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\FOXPRO\INIT; ValueType: string; Components: bde; ValueName: LANGDRIVER; ValueData: DBWINUS0; Flags: createvalueifdoesntexist

;Foxpro table create
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\FOXPRO\TABLE CREATE; ValueType: string; Components: bde; ValueName: LEVEL; ValueData: 25; Flags: createvalueifdoesntexist

;BDE INFORMIX
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: OPEN MODE; ValueData: READ/WRITE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: USER NAME; ValueData: MYNAME; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE SIZE; ValueData: 8; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: LANGDRIVER; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: SQLQRYMODE; ValueData: SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: SQLPASSTHRU MODE; ValueData: SHARED AUTOCOMMIT; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE TIME; ValueData: -1; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: ENABLE SCHEMA CACHE; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE DIR; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: ENABLE BCD; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: MAXROWS; ValueData: -1; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: BATCH COUNT; ValueData: 200; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: BLOBS TO CACHE; ValueData: 64; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: BLOB SIZE; ValueData: 32; Flags: createvalueifdoesntexist

Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: SERVER NAME; ValueData: INF_SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: DATABASE NAME; ValueData: MY_DATABASE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: LOCK MODE; ValueData: 5; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: DATE MODE; ValueData: 1; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: DATE SEPARATOR; ValueData: /; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: LIST SYNONYMS; ValueData: NONE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: DBNLS; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\DB OPEN; ValueType: string; Components: bde; ValueName: COLLCHAR; ValueData: ; Flags: createvalueifdoesntexist

;INFORMIX INIT
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\INIT; ValueType: string; Components: bde; ValueName: VERSION; ValueData: 4.0; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\INIT; ValueType: string; Components: bde; ValueName: TYPE; ValueData: SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\INIT; ValueType: string; Components: bde; ValueName: DLL32; ValueData: SQLINF9.DLL; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\INIT; ValueType: string; Components: bde; ValueName: DRIVER FLAGS; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INFORMIX\INIT; ValueType: string; Components: bde; ValueName: TRACE MODE; ValueData: 0; Flags: createvalueifdoesntexist


;BDE INTERBASE
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: OPEN MODE; ValueData: READ/WRITE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: USER NAME; ValueData: SYSDBA; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE SIZE; ValueData: 8; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: LANGDRIVER; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: SQLQRYMODE; ValueData: SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: SQLPASSTHRU MODE; ValueData: SHARED AUTOCOMMIT; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE TIME; ValueData: -1; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: ENABLE SCHEMA CACHE; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE DIR; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: ENABLE BCD; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: MAXROWS; ValueData: -1; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: BATCH COUNT; ValueData: 200; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: BLOBS TO CACHE; ValueData: 64; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: BLOB SIZE; ValueData: 32; Flags: createvalueifdoesntexist

Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: SERVER NAME; ValueData: IB_SERVER:/PATH/DATABASE.GDB; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: WAIT ON LOCKS; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: COMMIT RETAIN; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: ROLE NAME; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\DB OPEN; ValueType: string; Components: bde; ValueName: SQLDIALECT; ValueData: 1; Flags: createvalueifdoesntexist

;INTERBASE INIT
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\INIT; ValueType: string; Components: bde; ValueName: VERSION; ValueData: 4.0; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\INIT; ValueType: string; Components: bde; ValueName: TYPE; ValueData: SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\INIT; ValueType: string; Components: bde; ValueName: DLL32; ValueData: SQLINT32.DLL; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\INIT; ValueType: string; Components: bde; ValueName: DRIVER FLAGS; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\INTRBASE\INIT; ValueType: string; Components: bde; ValueName: TRACE MODE; ValueData: 0; Flags: createvalueifdoesntexist


;BDE MSACCESS
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\DB OPEN; ValueType: string; Components: bde; ValueName: OPEN MODE; ValueData: READ/WRITE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\DB OPEN; ValueType: string; Components: bde; ValueName: USER NAME; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\DB OPEN; ValueType: string; Components: bde; ValueName: LANGDRIVER; ValueData: ; Flags: createvalueifdoesntexist

Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\DB OPEN; ValueType: string; Components: bde; ValueName: DATABASE NAME; ValueData: DRIVE:/PATH/DATABASE.MDB; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\DB OPEN; ValueType: string; Components: bde; ValueName: SYSTEM DATABASE; ValueData: ; Flags: createvalueifdoesntexist

;MSACCESS INIT
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\INIT; ValueType: string; Components: bde; ValueName: VERSION; ValueData: 1.0; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\INIT; ValueType: string; Components: bde; ValueName: TYPE; ValueData: SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\INIT; ValueType: string; Components: bde; ValueName: DLL32; ValueData: IDDA3532.DLL; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\INIT; ValueType: string; Components: bde; ValueName: DRIVER FLAGS; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\INIT; ValueType: string; Components: bde; ValueName: TRACE MODE; ValueData: 0; Flags: createvalueifdoesntexist

;BDE MSSQL
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: OPEN MODE; ValueData: READ/WRITE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: USER NAME; ValueData: MYNAME; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE SIZE; ValueData: 8; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: LANGDRIVER; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: SQLQRYMODE; ValueData: SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: SQLPASSTHRU MODE; ValueData: SHARED AUTOCOMMIT; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE TIME; ValueData: -1; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: ENABLE SCHEMA CACHE; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE DIR; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: ENABLE BCD; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: MAXROWS; ValueData: -1; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: BATCH COUNT; ValueData: 200; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: BLOBS TO CACHE; ValueData: 64; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: BLOB SIZE; ValueData: 32; Flags: createvalueifdoesntexist

Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: DATABASE NAME; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: SERVER NAME; ValueData: MSS_SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: BLOB EDIT LOGGING; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: DATE MODE; ValueData: 0; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: MAX QUERY TIME; ValueData: 300; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: HOST NAME; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: APPLICATION NAME; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: NATIONAL LANG NAME; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\DB OPEN; ValueType: string; Components: bde; ValueName: TDS PACKET SIZE; ValueData: 4096; Flags: createvalueifdoesntexist

;MSSQL INIT
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\INIT; ValueType: string; Components: bde; ValueName: VERSION; ValueData: 4.0; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\INIT; ValueType: string; Components: bde; ValueName: TYPE; ValueData: SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\INIT; ValueType: string; Components: bde; ValueName: DLL32; ValueData: SQLMSS32.DLL; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\INIT; ValueType: string; Components: bde; ValueName: DRIVER FLAGS; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\INIT; ValueType: string; Components: bde; ValueName: TRACE MODE; ValueData: 0; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\INIT; ValueType: string; Components: bde; ValueName: VENDOR INIT; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\INIT; ValueType: string; Components: bde; ValueName: CONNECT TIMEOUT; ValueData: 30; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\INIT; ValueType: string; Components: bde; ValueName: TIMEOUT; ValueData: 300; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSSQL\INIT; ValueType: string; Components: bde; ValueName: MAX DBPROCESSES; ValueData: 31; Flags: createvalueifdoesntexist

;BDE ORACLE
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: OPEN MODE; ValueData: READ/WRITE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: USER NAME; ValueData: MYNAME; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE SIZE; ValueData: 8; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: LANGDRIVER; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: SQLQRYMODE; ValueData: SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: SQLPASSTHRU MODE; ValueData: SHARED AUTOCOMMIT; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE TIME; ValueData: -1; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: ENABLE SCHEMA CACHE; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE DIR; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: ENABLE BCD; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: MAXROWS; ValueData: -1; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: BATCH COUNT; ValueData: 200; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: BLOBS TO CACHE; ValueData: 64; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: BLOB SIZE; ValueData: 32; Flags: createvalueifdoesntexist

Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: SERVER NAME; ValueData: ORA_SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: NET PROTOCOL; ValueData: TNS; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: ENABLE INTEGERS; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: LIST SYNONYMS; ValueData: NONE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: ROWSET SIZE; ValueData: 20; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\DB OPEN; ValueType: string; Components: bde; ValueName: OBJECT MODE; ValueData: TRUE; Flags: createvalueifdoesntexist

;ORACLE INIT
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\INIT; ValueType: string; Components: bde; ValueName: VERSION; ValueData: 4.0; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\INIT; ValueType: string; Components: bde; ValueName: TYPE; ValueData: SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\INIT; ValueType: string; Components: bde; ValueName: DLL32; ValueData: SQLORA32.DLL; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\INIT; ValueType: string; Components: bde; ValueName: VENDOR INIT; ValueData: ORA73.DLL; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\INIT; ValueType: string; Components: bde; ValueName: DRIVER FLAGS; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\ORACLE\INIT; ValueType: string; Components: bde; ValueName: TRACE MODE; ValueData: 0; Flags: createvalueifdoesntexist


;Paradox INIT
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\PARADOX\INIT; ValueType: string; Components: bde; ValueName: VERSION; ValueData: 4.0; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\PARADOX\INIT; ValueType: string; Components: bde; ValueName: TYPE; ValueData: FILE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\PARADOX\INIT; ValueType: string; Components: bde; ValueName: LANGDRIVER; ValueData: ANSISPAN; Flags: createvalueifdoesntexist

;DBase table create
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\PARADOX\TABLE CREATE; ValueType: string; Components: bde; ValueName: LEVEL; ValueData: 7; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\PARADOX\TABLE CREATE; ValueType: string; Components: bde; ValueName: BLOCK SIZE; ValueData: 2048; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\PARADOX\TABLE CREATE; ValueType: string; Components: bde; ValueName: FILL FACTOR; ValueData: 95; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\PARADOX\TABLE CREATE; ValueType: string; Components: bde; ValueName: STRICTINTEGRTY; ValueData: TRUE; Flags: createvalueifdoesntexist


;BDE SYBASE
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: OPEN MODE; ValueData: READ/WRITE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: USER NAME; ValueData: MYNAME; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE SIZE; ValueData: 8; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: LANGDRIVER; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: SQLQRYMODE; ValueData: SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: SQLPASSTHRU MODE; ValueData: SHARED AUTOCOMMIT; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE TIME; ValueData: -1; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: ENABLE SCHEMA CACHE; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: SCHEMA CACHE DIR; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: ENABLE BCD; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: MAXROWS; ValueData: -1; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: BATCH COUNT; ValueData: 200; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: BLOBS TO CACHE; ValueData: 64; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: BLOB SIZE; ValueData: 32; Flags: createvalueifdoesntexist

Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: DATABASE NAME; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: SERVER NAME; ValueData: MSS_SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: BLOB EDIT LOGGING; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: DATE MODE; ValueData: 1; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: MAX QUERY TIME; ValueData: 300; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: HOST NAME; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: APPLICATION NAME; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: NATIONAL LANG NAME; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: TDS PACKET SIZE; ValueData: 512; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\DB OPEN; ValueType: string; Components: bde; ValueName: CS CURSOR ROWS; ValueData: 1; Flags: createvalueifdoesntexist

;SYBASE INIT
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\INIT; ValueType: string; Components: bde; ValueName: VERSION; ValueData: 4.0; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\INIT; ValueType: string; Components: bde; ValueName: TYPE; ValueData: SERVER; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\INIT; ValueType: string; Components: bde; ValueName: DLL32; ValueData: SQLSSC32.DLL; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\INIT; ValueType: string; Components: bde; ValueName: DRIVER FLAGS; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\INIT; ValueType: string; Components: bde; ValueName: TRACE MODE; ValueData: 0; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\INIT; ValueType: string; Components: bde; ValueName: VENDOR INIT; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\INIT; ValueType: string; Components: bde; ValueName: CONNECT TIMEOUT; ValueData: 30; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\INIT; ValueType: string; Components: bde; ValueName: TIMEOUT; ValueData: 300; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\SYBASE\INIT; ValueType: string; Components: bde; ValueName: MAX DBPROCESSES; ValueData: 31; Flags: createvalueifdoesntexist

; LOCAL CONFIG FORMATS
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\DATE; ValueType: string; Components: bde; ValueName: SEPARATOR; ValueData: /; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\DATE; ValueType: string; Components: bde; ValueName: MODE; ValueData: 1; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\DATE; ValueType: string; Components: bde; ValueName: FOURDIGITYEAR; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\DATE; ValueType: string; Components: bde; ValueName: YEARBIASED; ValueData: TRUE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\DATE; ValueType: string; Components: bde; ValueName: LEADINGZEROM; ValueData: TRUE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\DATE; ValueType: string; Components: bde; ValueName: LEADINGZEROD; ValueData: FALSE; Flags: createvalueifdoesntexist

Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\NUMBER; ValueType: string; Components: bde; ValueName: DECIMALSEPARATOR; ValueData: ,; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\NUMBER; ValueType: string; Components: bde; ValueName: THOUSANDSEPARATOR; ValueData: .; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\NUMBER; ValueType: string; Components: bde; ValueName: DECIMALDIGITS; ValueData: 2; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\NUMBER; ValueType: string; Components: bde; ValueName: LEADINGZERON; ValueData: FALSE; Flags: createvalueifdoesntexist

Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\TIME; ValueType: string; Components: bde; ValueName: TWELVEHOUR; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\TIME; ValueType: string; Components: bde; ValueName: AMSTRING; ValueData: AM; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\TIME; ValueType: string; Components: bde; ValueName: PMSTRING; ValueData: PM; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\TIME; ValueType: string; Components: bde; ValueName: SECONDS; ValueData: TRUE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\TIME; ValueType: string; Components: bde; ValueName: MILSECONDS; ValueData: FALSE; Flags: createvalueifdoesntexist

; GENERAL INIT

Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: VERSION; ValueData: 4.0; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: LOCAL SHARE; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: MINBUFSIZE; ValueData: 128; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: MAXBUFSIZE; ValueData: 2048; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: LANGDRIVER; ValueData: ANSISPAN; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: MAXFILEHANDLES; ValueData: 48; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: SYSFLAGS; ValueData: 0; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: LOW MEMORY USAGE LIMIT; ValueData: 32; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: AUTO ODBC; ValueData: FALSE; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: DEFAULT DRIVER; ValueData: PARADOX; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: MEMSIZE; ValueData: 16; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: SHAREDMEMSIZE; ValueData: 2048; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: SHAREDMEMLOCATION; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: DATA REPOSITORY; ValueData: Sample Data Dictionary; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: SQLQRYMODE; ValueData: ; Flags: createvalueifdoesntexist
Root: HKLM; Subkey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; Components: bde; ValueName: MTS POOLING; ValueData: FALSE; Flags: createvalueifdoesntexist

[Icons]
Name: {group}\{cm:DesignerXP}; Filename: {app}\repmandxp.exe; Components: designer; WorkingDir: {app}
Name: {group}\{cm:MetafileViewerandReportClientXP}; Filename: {app}\metaviewxp.exe; Components: clienttcp; WorkingDir: {app}
Name: {group}\{cm:TranslationUtility}; Filename: {app}\rptranslate.exe; Components: translation; WorkingDir: {app}
Name: {group}\{cm:SLicense}; Filename: {app}\license.txt
Name: {group}\{cm:ServerapplicationXP}; Filename: {app}\reportserverappxp.exe; Components: servertcp; WorkingDir: {app}
Name: {group}\{cm:ServerconfigurationXP}; Filename: {app}\repserverconfigxp.exe; Components: serverconf; WorkingDir: {app}
Name: {group}\{cm:ServiceInstallationtool}; Filename: {app}\repserviceinstall.exe; Components: servertcp; WorkingDir: {app}
Name: {group}\{cm:RegisterActiveX}; Filename: {sys}\regsvr32; Parameters: Reportman.ocx; Components: activex; WorkingDir: {app}
Name: {group}\{cm:UnRegisterActiveX}; Filename: {sys}\regsvr32; Parameters: /u Reportman.ocx; Components: activex; WorkingDir: {app}
Name: {group}\{cm:RegisterPlugin}; Filename: {sys}\regsvr32; Parameters: WebReportmanX.ocx; Components: ieplugin; WorkingDir: {app}
Name: {group}\{cm:UnRegisterPlugin}; Filename: {sys}\regsvr32; Parameters: /u WebReportmanX.ocx; Components: ieplugin; WorkingDir: {app}
Name: {userdesktop}\{cm:ReportManagerDesignerXP}; Filename: {app}\repmandxp.exe; WorkingDir: {app}; Components: designer; MinVersion: 4,4; Tasks: desktopicon
Name: {userdesktop}\{cm:ReportManagerClient}; Filename: {app}\metaviewxp.exe; WorkingDir: {app}; Components: clienttcp; MinVersion: 4,4; Tasks: desktopicon

[Run]
;Windows Vista compatibility
;Filename: {app}\repmandxp.exe; Description: {cm:LaunchReportManagerDesignerXP}; Components: designer; Flags: nowait postinstall skipifsilent
