program T2TiERPContabilidade;

uses
  Forms,
  Windows,
  Dialogs,
  Tipos in '..\Comum\Tipos.pas',
  Conversor in '..\Comum\Conversor.pas',
  NotificationService in '..\Comum\NotificationService.pas',
  SessaoUsuario in '..\Comum\SessaoUsuario.pas',
  UsuarioController in '..\Comum\Controller\UsuarioController.pas',
  Controller in '..\Comum\Controller\Controller.pas',
  FuncaoController in '..\Comum\Controller\FuncaoController.pas',
  PapelController in '..\Comum\Controller\PapelController.pas',
  PapelFuncaoController in '..\Comum\Controller\PapelFuncaoController.pas',
  UTelaCadastro in '..\Comum\Tela\UTelaCadastro.pas' {FTelaCadastro},
  UTela in '..\Comum\Tela\UTela.pas' {FTela},
  ULookup in '..\Comum\Tela\ULookup.pas' {FLookup},
  UBase in '..\Comum\Tela\UBase.pas' {FBase},
  UDataModule in '..\Comum\Tela\UDataModule.pas' {FDataModule: TDataModule},
  UFiltro in '..\Comum\Tela\UFiltro.pas' {FFiltro},
  ULogin in '..\Comum\Tela\ULogin.pas' {FLogin},
  UMenu in 'Tela\UMenu.pas' {FMenu},
  Biblioteca in '..\..\Comum\Biblioteca.pas',
  Constantes in '..\..\Comum\Constantes.pas',
  FuncaoVO in '..\..\Comum\VO\FuncaoVO.pas',
  JSonVO in '..\..\Comum\VO\JSonVO.pas',
  UsuarioVO in '..\..\Comum\VO\UsuarioVO.pas',
  PapelVO in '..\..\Comum\VO\PapelVO.pas',
  PapelFuncaoVO in '..\..\Comum\VO\PapelFuncaoVO.pas',
  PessoaVO in '..\..\Comum\VO\PessoaVO.pas',
  EnderecoVO in '..\..\Comum\VO\EnderecoVO.pas',
  ContatoVO in '..\..\Comum\VO\ContatoVO.pas',
  PessoaFisicaVO in '..\..\Comum\VO\PessoaFisicaVO.pas',
  PessoaJuridicaVO in '..\..\Comum\VO\PessoaJuridicaVO.pas',
  ColaboradorVO in '..\..\Comum\VO\ColaboradorVO.pas',
  SetorVO in '..\..\Comum\VO\SetorVO.pas',
  CargoVO in '..\..\Comum\VO\CargoVO.pas',
  EmpresaVO in '..\..\Comum\VO\EmpresaVO.pas',
  UfVO in '..\..\Comum\VO\UfVO.pas',
  PaisVO in '..\..\Comum\VO\PaisVO.pas',
  ContadorVO in '..\..\Comum\VO\ContadorVO.pas',
  FpasVO in '..\..\Comum\VO\FpasVO.pas',
  SindicatoVO in '..\..\Comum\VO\SindicatoVO.pas',
  NivelFormacaoVO in '..\..\Comum\VO\NivelFormacaoVO.pas',
  TipoColaboradorVO in '..\..\Comum\VO\TipoColaboradorVO.pas',
  RegistroCartorioController in 'Controller\RegistroCartorioController.pas',
  RegistroCartorioVO in '..\..\Comum\VO\RegistroCartorioVO.pas',
  URegistroCartorio in 'Tela\URegistroCartorio.pas' {FRegistroCartorio},
  SituacaoColaboradorVO in '..\..\Comum\VO\SituacaoColaboradorVO.pas',
  TipoAdmissaoVO in '..\..\Comum\VO\TipoAdmissaoVO.pas',
  ContabilParametrosVO in '..\..\Comum\VO\ContabilParametrosVO.pas',
  ContabilParametrosController in 'Controller\ContabilParametrosController.pas',
  UContabilParametros in 'Tela\UContabilParametros.pas' {FContabilParametros},
  ContabilIndiceVO in '..\..\Comum\VO\ContabilIndiceVO.pas',
  ContabilIndiceValorVO in '..\..\Comum\VO\ContabilIndiceValorVO.pas',
  ContabilIndiceController in 'Controller\ContabilIndiceController.pas',
  UContabilIndice in 'Tela\UContabilIndice.pas' {FContabilIndice},
  IndiceEconomicoController in 'Controller\IndiceEconomicoController.pas',
  IndiceEconomicoVO in '..\..\Comum\VO\IndiceEconomicoVO.pas',
  ContabilHistoricoController in 'Controller\ContabilHistoricoController.pas',
  ContabilHistoricoVO in '..\..\Comum\VO\ContabilHistoricoVO.pas',
  UContabilHistorico in 'Tela\UContabilHistorico.pas' {FContabilHistorico},
  UAidfAimdf in 'Tela\UAidfAimdf.pas' {FAidfAimdf},
  AidfAimdfController in 'Controller\AidfAimdfController.pas',
  AidfAimdfVO in '..\..\Comum\VO\AidfAimdfVO.pas',
  FapController in 'Controller\FapController.pas',
  FapVO in '..\..\Comum\VO\FapVO.pas',
  UFap in 'Tela\UFap.pas' {FFap},
  UPlanoConta in 'Tela\UPlanoConta.pas' {FPlanoConta},
  PlanoContaController in 'Controller\PlanoContaController.pas',
  PlanoContaVO in '..\..\Comum\VO\PlanoContaVO.pas',
  UPlanoContaRefSped in 'Tela\UPlanoContaRefSped.pas' {FPlanoContaRefSped},
  PlanoContaRefSpedController in 'Controller\PlanoContaRefSpedController.pas',
  PlanoContaRefSpedVO in '..\..\Comum\VO\PlanoContaRefSpedVO.pas',
  UContabilConta in 'Tela\UContabilConta.pas' {FContabilConta},
  ContabilContaController in 'Controller\ContabilContaController.pas',
  ContabilContaVO in '..\..\Comum\VO\ContabilContaVO.pas',
  ContabilLancamentoPadraoController in 'Controller\ContabilLancamentoPadraoController.pas',
  ContabilLancamentoPadraoVO in '..\..\Comum\VO\ContabilLancamentoPadraoVO.pas',
  UContabilLancamentoPadrao in 'Tela\UContabilLancamentoPadrao.pas' {FContabilLancamentoPadrao},
  ContabilLoteController in 'Controller\ContabilLoteController.pas',
  ContabilLoteVO in '..\..\Comum\VO\ContabilLoteVO.pas',
  UContabilLote in 'Tela\UContabilLote.pas' {FContabilLote},
  ContabilLancamentoOrcadoController in 'Controller\ContabilLancamentoOrcadoController.pas',
  ContabilLancamentoOrcadoVO in '..\..\Comum\VO\ContabilLancamentoOrcadoVO.pas',
  UContabilLancamentoOrcado in 'Tela\UContabilLancamentoOrcado.pas' {FContabilLancamentoOrcado},
  ContabilLancamentoCabecalhoController in 'Controller\ContabilLancamentoCabecalhoController.pas',
  ContabilLancamentoDetalheVO in '..\..\Comum\VO\ContabilLancamentoDetalheVO.pas',
  ContabilLancamentoCabecalhoVO in '..\..\Comum\VO\ContabilLancamentoCabecalhoVO.pas',
  UContabilLancamento in 'Tela\UContabilLancamento.pas' {FContabilLancamento},
  ContabilFechamentoVO in '..\..\Comum\VO\ContabilFechamentoVO.pas',
  ContabilFechamentoController in 'Controller\ContabilFechamentoController.pas',
  UContabilFechamento in 'Tela\UContabilFechamento.pas' {FContabilFechamento},
  ContabilDreCabecalhoController in 'Controller\ContabilDreCabecalhoController.pas',
  ContabilDreCabecalhoVO in '..\..\Comum\VO\ContabilDreCabecalhoVO.pas',
  ContabilDreDetalheVO in '..\..\Comum\VO\ContabilDreDetalheVO.pas',
  UContabilDre in 'Tela\UContabilDre.pas' {FContabilDre},
  UContabilDfc in 'Tela\UContabilDfc.pas' {FContabilDfc},
  UContabilBalancoPatrimonial in 'Tela\UContabilBalancoPatrimonial.pas' {FContabilBalancoPatrimonial},
  ContabilEncerramentoExeCabController in 'Controller\ContabilEncerramentoExeCabController.pas',
  ContabilEncerramentoExeCabVO in '..\..\Comum\VO\ContabilEncerramentoExeCabVO.pas',
  ContabilEncerramentoExeDetVO in '..\..\Comum\VO\ContabilEncerramentoExeDetVO.pas',
  UContabilEncerramentoExercicio in 'Tela\UContabilEncerramentoExercicio.pas' {FContabilEncerramentoExercicio},
  ContabilTermoVO in '..\..\Comum\VO\ContabilTermoVO.pas',
  ContabilLivroVO in '..\..\Comum\VO\ContabilLivroVO.pas',
  ContabilLivroController in 'Controller\ContabilLivroController.pas',
  UContabilLivro in 'Tela\UContabilLivro.pas' {FContabilLivro},
  UContabilLivrosContabeis in 'Tela\UContabilLivrosContabeis.pas' {FContabilLivrosContabeis},
  Atributos in '..\..\Comum\Atributos.pas',
  EmpresaController in '..\Comum\Controller\EmpresaController.pas',
  ViewSessaoEmpresaController in '..\Comum\Controller\ViewSessaoEmpresaController.pas',
  AdministrativoFormularioVO in '..\..\Comum\VO\AdministrativoFormularioVO.pas',
  EmpresaSessaoVO in '..\..\Comum\VO\EmpresaSessaoVO.pas',
  ViewSessaoEmpresaVO in '..\..\Comum\VO\ViewSessaoEmpresaVO.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'T2Ti ERP Contabilidade';
  Application.CreateForm(TFMenu, FMenu);
  Application.CreateForm(TFDataModule, FDataModule);
  Application.Run;
end.
