; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Report Manager ActiveX plugin
AppVerName=Report Manager ActiveX plugin 2.8a
AppVersion=2.8a
OutputBaseFilename=reportmaplugin2_8a
AppPublisher=Toni Martir
AppPublisherURL=http://reportman.sourceforge.net
AppSupportURL=http://sourceforge.net/projects/reportman
AppUpdatesURL=http://sourceforge.net/projects/reportman
DefaultDirName={pf}\Report Manager
DefaultGroupName=Report Manager
LicenseFile=license.txt
PrivilegesRequired=admin
LanguageDetectionMethod=uilanguage
WizardImageFile=HardwareClassic05.bmp
WizardImageStretch=False
WizardSmallImageFile=SetupModernSmall02.bmp
CreateAppDir=no
; uncomment the following line if you want your installation to run on NT 3.51 too.
; MinVersion=4,3.51

;[Types]
;Name: full; Description: {cm:Fullinstallation}
;Name: custom; Description: {cm:Custominstallation}; Flags: iscustom

;[Components]
;Name: ieplugin; Description: {cm:InternetExplorerplugin}; Types: full custom

[Languages]
Name: en; MessagesFile: EnglishT.isl
Name: de; MessagesFile: GermanT.isl
Name: es; MessagesFile: SpanishT.isl
Name: cat; MessagesFile: CatalanT.isl
Name: pt; MessagesFile: PortugueseT.isl
Name: it; MessagesFile: ItalianT.isl
Name: fr; MessagesFile: FrenchT.isl

[Files]
Source: ..\repman\reportmanres.*; DestDir: {sys}; Flags: restartreplace
;Source: license.txt; DestDir: {app}; Flags: ignoreversion
Source: ..\drivers\win32\upx.exe; DestDir: {sys}; Flags: restartreplace
Source: ..\webactivex\WebReportManX.ocx; DestDir: {sys}; Flags: restartreplace sharedfile regserver ignoreversion



;[Icons]
;Name: {group}\{cm:RegisterPlugin}; Filename: {sys}\regsvr32; Parameters: WebReportmanX.ocx; Components: ieplugin; WorkingDir: {app}
;Name: {group}\{cm:UnRegisterPlugin}; Filename: {sys}\regsvr32; Parameters: /u WebReportmanX.ocx; Components: ieplugin; WorkingDir: {app}
;Name: {group}\{cm:SLicense}; Filename: {app}\license.txt
