program T2TiERPOrcamentos;

uses
  Forms,
  Windows,
  Dialogs,
  Tipos in '..\Comum\Tipos.pas',
  Conversor in '..\Comum\Conversor.pas',
  NotificationService in '..\Comum\NotificationService.pas',
  SessaoUsuario in '..\Comum\SessaoUsuario.pas',
  UsuarioController in '..\Comum\Controller\UsuarioController.pas',
  Controller in '..\Comum\Controller\Controller.pas',
  FuncaoController in '..\Comum\Controller\FuncaoController.pas',
  PapelController in '..\Comum\Controller\PapelController.pas',
  PapelFuncaoController in '..\Comum\Controller\PapelFuncaoController.pas',
  UTelaCadastro in '..\Comum\Tela\UTelaCadastro.pas' {FTelaCadastro},
  UTela in '..\Comum\Tela\UTela.pas' {FTela},
  ULookup in '..\Comum\Tela\ULookup.pas' {FLookup},
  UBase in '..\Comum\Tela\UBase.pas' {FBase},
  UDataModule in '..\Comum\Tela\UDataModule.pas' {FDataModule: TDataModule},
  UFiltro in '..\Comum\Tela\UFiltro.pas' {FFiltro},
  ULogin in '..\Comum\Tela\ULogin.pas' {FLogin},
  UMenu in 'Tela\UMenu.pas' {FMenu},
  Atributos in '..\..\Comum\Atributos.pas',
  Biblioteca in '..\..\Comum\Biblioteca.pas',
  Constantes in '..\..\Comum\Constantes.pas',
  FuncaoVO in '..\..\Comum\VO\FuncaoVO.pas',
  JSonVO in '..\..\Comum\VO\JSonVO.pas',
  UsuarioVO in '..\..\Comum\VO\UsuarioVO.pas',
  PapelVO in '..\..\Comum\VO\PapelVO.pas',
  PapelFuncaoVO in '..\..\Comum\VO\PapelFuncaoVO.pas',
  PessoaVO in '..\..\Comum\VO\PessoaVO.pas',
  EnderecoVO in '..\..\Comum\VO\EnderecoVO.pas',
  ContatoVO in '..\..\Comum\VO\ContatoVO.pas',
  PessoaFisicaVO in '..\..\Comum\VO\PessoaFisicaVO.pas',
  PessoaJuridicaVO in '..\..\Comum\VO\PessoaJuridicaVO.pas',
  ColaboradorVO in '..\..\Comum\VO\ColaboradorVO.pas',
  SetorVO in '..\..\Comum\VO\SetorVO.pas',
  CargoVO in '..\..\Comum\VO\CargoVO.pas',
  EmpresaVO in '..\..\Comum\VO\EmpresaVO.pas',
  UfVO in '..\..\Comum\VO\UfVO.pas',
  PaisVO in '..\..\Comum\VO\PaisVO.pas',
  ContadorVO in '..\..\Comum\VO\ContadorVO.pas',
  FpasVO in '..\..\Comum\VO\FpasVO.pas',
  SindicatoVO in '..\..\Comum\VO\SindicatoVO.pas',
  NivelFormacaoVO in '..\..\Comum\VO\NivelFormacaoVO.pas',
  TipoColaboradorVO in '..\..\Comum\VO\TipoColaboradorVO.pas',
  SituacaoColaboradorVO in '..\..\Comum\VO\SituacaoColaboradorVO.pas',
  TipoAdmissaoVO in '..\..\Comum\VO\TipoAdmissaoVO.pas',
  UOrcamentoEmpresarial in 'Tela\UOrcamentoEmpresarial.pas' {FOrcamentoEmpresarial},
  UOrcamentoPeriodo in 'Tela\UOrcamentoPeriodo.pas' {FOrcamentoPeriodo},
  OrcamentoDetalheController in 'Controller\OrcamentoDetalheController.pas',
  OrcamentoEmpresarialController in 'Controller\OrcamentoEmpresarialController.pas',
  OrcamentoPeriodoController in 'Controller\OrcamentoPeriodoController.pas',
  OrcamentoPeriodoVO in '..\..\Comum\VO\OrcamentoPeriodoVO.pas',
  NaturezaFinanceiraVO in '..\..\Comum\VO\NaturezaFinanceiraVO.pas',
  NaturezaFinanceiraController in '..\Contas a Pagar\Controller\NaturezaFinanceiraController.pas',
  CentroResultadoVO in '..\..\Comum\VO\CentroResultadoVO.pas',
  ContabilContaVO in '..\..\Comum\VO\ContabilContaVO.pas',
  PlanoNaturezaFinanceiraVO in '..\..\Comum\VO\PlanoNaturezaFinanceiraVO.pas',
  PlanoCentroResultadoVO in '..\..\Comum\VO\PlanoCentroResultadoVO.pas',
  OrcamentoEmpresarialVO in '..\..\Comum\VO\OrcamentoEmpresarialVO.pas',
  OrcamentoDetalheVO in '..\..\Comum\VO\OrcamentoDetalheVO.pas',
  VendedorVO in '..\..\Comum\VO\VendedorVO.pas',
  TransportadoraVO in '..\..\Comum\VO\TransportadoraVO.pas',
  TipoNotaFiscalVO in '..\..\Comum\VO\TipoNotaFiscalVO.pas',
  ClienteVO in '..\..\Comum\VO\ClienteVO.pas',
  TributOperacaoFiscalVO in '..\..\Comum\VO\TributOperacaoFiscalVO.pas',
  AtividadeForCliVO in '..\..\Comum\VO\AtividadeForCliVO.pas',
  SituacaoForCliVO in '..\..\Comum\VO\SituacaoForCliVO.pas',
  AdministrativoFormularioVO in '..\..\Comum\VO\AdministrativoFormularioVO.pas',
  PlanoNaturezaFinanceiraController in 'Controller\PlanoNaturezaFinanceiraController.pas',
  EmpresaSessaoVO in '..\..\Comum\VO\EmpresaSessaoVO.pas',
  EmpresaController in '..\Comum\Controller\EmpresaController.pas',
  ViewSessaoEmpresaController in '..\Comum\Controller\ViewSessaoEmpresaController.pas',
  ViewSessaoEmpresaVO in '..\..\Comum\VO\ViewSessaoEmpresaVO.pas',
  FinLancamentoPagarVO in '..\..\Comum\VO\FinLancamentoPagarVO.pas',
  FinLancamentoReceberVO in '..\..\Comum\VO\FinLancamentoReceberVO.pas',
  FinLctoPagarNtFinanceiraVO in '..\..\Comum\VO\FinLctoPagarNtFinanceiraVO.pas',
  FinLctoReceberNtFinanceiraVO in '..\..\Comum\VO\FinLctoReceberNtFinanceiraVO.pas',
  FinLancamentoPagarController in 'Controller\FinLancamentoPagarController.pas',
  FinLancamentoReceberController in 'Controller\FinLancamentoReceberController.pas',
  FinDocumentoOrigemVO in '..\..\Comum\VO\FinDocumentoOrigemVO.pas',
  FinParcelaReceberVO in '..\..\Comum\VO\FinParcelaReceberVO.pas',
  FinParcelaPagarVO in '..\..\Comum\VO\FinParcelaPagarVO.pas',
  ContaCaixaVO in '..\..\Comum\VO\ContaCaixaVO.pas',
  BancoVO in '..\..\Comum\VO\BancoVO.pas',
  AgenciaBancoVO in '..\..\Comum\VO\AgenciaBancoVO.pas',
  ClientePessoaVO in '..\..\Comum\VO\ClientePessoaVO.pas',
  FornecedorPessoaVO in '..\..\Comum\VO\FornecedorPessoaVO.pas',
  FinParcelaPagamentoVO in '..\..\Comum\VO\FinParcelaPagamentoVO.pas',
  FinParcelaRecebimentoVO in '..\..\Comum\VO\FinParcelaRecebimentoVO.pas',
  FinTipoPagamentoVO in '..\..\Comum\VO\FinTipoPagamentoVO.pas',
  FinTipoRecebimentoVO in '..\..\Comum\VO\FinTipoRecebimentoVO.pas',
  FinChequeEmitidoVO in '..\..\Comum\VO\FinChequeEmitidoVO.pas',
  FinChequeRecebidoVO in '..\..\Comum\VO\FinChequeRecebidoVO.pas',
  ChequeVO in '..\..\Comum\VO\ChequeVO.pas',
  TalonarioChequeVO in '..\..\Comum\VO\TalonarioChequeVO.pas',
  UOrcamentoFluxoCaixaPeriodo in 'Tela\UOrcamentoFluxoCaixaPeriodo.pas' {FOrcamentoFluxoCaixaPeriodo},
  OrcamentoFluxoCaixaPeriodoController in 'Controller\OrcamentoFluxoCaixaPeriodoController.pas',
  OrcamentoFluxoCaixaPeriodoVO in '..\..\Comum\VO\OrcamentoFluxoCaixaPeriodoVO.pas',
  ContaCaixaController in '..\Cadastros Base\Controller\ContaCaixaController.pas',
  UOrcamentoFinanceiroCaixa in 'Tela\UOrcamentoFinanceiroCaixa.pas' {FOrcamentoFinanceiroCaixa},
  OrcamentoFluxoCaixaController in 'Controller\OrcamentoFluxoCaixaController.pas',
  OrcamentoFluxoCaixaVO in '..\..\Comum\VO\OrcamentoFluxoCaixaVO.pas',
  OrcamentoFluxoCaixaDetalheVO in '..\..\Comum\VO\OrcamentoFluxoCaixaDetalheVO.pas',
  OrcamentoFluxoCaixaDetalheController in 'Controller\OrcamentoFluxoCaixaDetalheController.pas',
  ViewFinTotalPagamentosDiaVO in '..\..\Comum\VO\ViewFinTotalPagamentosDiaVO.pas',
  ViewFinTotalRecebimentosDiaVO in '..\..\Comum\VO\ViewFinTotalRecebimentosDiaVO.pas',
  ViewFinTotalPagamentosDiaController in 'Controller\ViewFinTotalPagamentosDiaController.pas',
  ViewFinTotalRecebimentosDiaController in 'Controller\ViewFinTotalRecebimentosDiaController.pas',
  ColaboradorPessoaVO in '..\..\Comum\VO\ColaboradorPessoaVO.pas',
  PessoaFisicaJuridicaVO in '..\..\Comum\VO\PessoaFisicaJuridicaVO.pas',
  CfopVO in '..\..\Comum\VO\CfopVO.pas',
  PlanoContaVO in '..\..\Comum\VO\PlanoContaVO.pas',
  PlanoContaRefSpedVO in '..\..\Comum\VO\PlanoContaRefSpedVO.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'T2Ti ERP Orçamentos';
  Application.CreateForm(TFMenu, FMenu);
  Application.CreateForm(TFDataModule, FDataModule);
  Application.Run;
end.
