// Do not edit. This file is machine generated by the Resource DLL Wizard.

library repmand;

{$R *.RES}
{ITE} {LCID:00000409:00000C0A} {}
{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpfparamsvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpgdidriver.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfgridvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdprintconfigvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rppagesetupvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rprfvparams.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpvpreview.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpdbxconfig.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpexpredlg.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpfparams.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpgraphutils.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfabout.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfdatainfo.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfdesign.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfgrid.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfhelpform.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfmain.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfsampledata.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfstruc.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdobjinsp.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdprintconfig.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rppagesetup.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rppreview.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpprintdia.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpqtdriver.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rprfparams.xfm}
{ITE} {RCFileType} {repmand_DRC.rc}

{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpfparamsvcl.dfm' FRpParamsVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpgdidriver.dfm' FRpVCLProgress:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfgridvcl.dfm' FRpGridOptionsVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdprintconfigvcl.dfm' FRpPrinterConfigVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rppagesetupvcl.dfm' FRpPageSetupVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rprfvparams.dfm' FRpRTParams:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpvpreview.dfm' FRpVPreview:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpdbxconfig.xfm' FRpDBXConfig:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpexpredlg.xfm' FrpExpredialog:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpfparams.xfm' FRpParams:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpgraphutils.xfm' FRpMessageDlg:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfabout.xfm' FRpAboutBox:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfdatainfo.xfm' FRpDatainfoconfig:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfdesign.xfm' FRpDesignFrame:TFrame}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfgrid.xfm' FRpGridOptions:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfhelpform.xfm' FRpHelpForm:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfmain.xfm' FRpMainF:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfsampledata.xfm' FRpShowSampledata:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfstruc.xfm' FRpStructure:TFrame}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdobjinsp.xfm' FRpObjInsp:TFrame}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdprintconfig.xfm' FRpPrinterConfig:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rppagesetup.xfm' FRpPageSetup:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rppreview.xfm' FRpPreview:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpprintdia.xfm' FRpPrintDialog:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpqtdriver.xfm' FRpQtProgress:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rprfparams.xfm' FRpRunTimeParams:TForm}
{$R 'repmand_DRC.res' 'repmand_DRC.rc'}

{$E ESN}

begin
end.