program T2TiERPCompras;

uses
  Forms,
  Windows,
  Dialogs,
  Tipos in '..\Comum\Tipos.pas',
  Conversor in '..\Comum\Conversor.pas',
  NotificationService in '..\Comum\NotificationService.pas',
  SessaoUsuario in '..\Comum\SessaoUsuario.pas',
  UsuarioController in '..\Comum\Controller\UsuarioController.pas',
  Controller in '..\Comum\Controller\Controller.pas',
  FuncaoController in '..\Comum\Controller\FuncaoController.pas',
  PapelController in '..\Comum\Controller\PapelController.pas',
  PapelFuncaoController in '..\Comum\Controller\PapelFuncaoController.pas',
  UTelaCadastro in '..\Comum\Tela\UTelaCadastro.pas' {FTelaCadastro},
  UTela in '..\Comum\Tela\UTela.pas' {FTela},
  ULookup in '..\Comum\Tela\ULookup.pas' {FLookup},
  UBase in '..\Comum\Tela\UBase.pas' {FBase},
  UDataModule in '..\Comum\Tela\UDataModule.pas' {FDataModule: TDataModule},
  UFiltro in '..\Comum\Tela\UFiltro.pas' {FFiltro},
  ULogin in '..\Comum\Tela\ULogin.pas' {FLogin},
  UMenu in 'Tela\UMenu.pas' {FMenu},
  Atributos in '..\..\Comum\Atributos.pas',
  Biblioteca in '..\..\Comum\Biblioteca.pas',
  Constantes in '..\..\Comum\Constantes.pas',
  FuncaoVO in '..\..\Comum\VO\FuncaoVO.pas',
  JSonVO in '..\..\Comum\VO\JSonVO.pas',
  UsuarioVO in '..\..\Comum\VO\UsuarioVO.pas',
  PapelVO in '..\..\Comum\VO\PapelVO.pas',
  PapelFuncaoVO in '..\..\Comum\VO\PapelFuncaoVO.pas',
  PessoaVO in '..\..\Comum\VO\PessoaVO.pas',
  EnderecoVO in '..\..\Comum\VO\EnderecoVO.pas',
  ContatoVO in '..\..\Comum\VO\ContatoVO.pas',
  PessoaFisicaVO in '..\..\Comum\VO\PessoaFisicaVO.pas',
  PessoaJuridicaVO in '..\..\Comum\VO\PessoaJuridicaVO.pas',
  ColaboradorVO in '..\..\Comum\VO\ColaboradorVO.pas',
  SetorVO in '..\..\Comum\VO\SetorVO.pas',
  CargoVO in '..\..\Comum\VO\CargoVO.pas',
  EmpresaVO in '..\..\Comum\VO\EmpresaVO.pas',
  UfVO in '..\..\Comum\VO\UfVO.pas',
  PaisVO in '..\..\Comum\VO\PaisVO.pas',
  ContadorVO in '..\..\Comum\VO\ContadorVO.pas',
  FpasVO in '..\..\Comum\VO\FpasVO.pas',
  SindicatoVO in '..\..\Comum\VO\SindicatoVO.pas',
  NivelFormacaoVO in '..\..\Comum\VO\NivelFormacaoVO.pas',
  TipoColaboradorVO in '..\..\Comum\VO\TipoColaboradorVO.pas',
  ContabilContaVO in '..\..\Comum\VO\ContabilContaVO.pas',
  UCompraTipoRequisicao in 'Tela\UCompraTipoRequisicao.pas' {FCompraTipoRequisicao},
  CompraTipoRequisicaoVO in '..\..\Comum\VO\CompraTipoRequisicaoVO.pas',
  CompraRequisicaoDetalheVO in '..\..\Comum\VO\CompraRequisicaoDetalheVO.pas',
  CompraRequisicaoVO in '..\..\Comum\VO\CompraRequisicaoVO.pas',
  UCompraRequisicao in 'Tela\UCompraRequisicao.pas' {FCompraRequisicao},
  ProdutoVO in '..\..\Comum\VO\ProdutoVO.pas',
  UnidadeProdutoVO in '..\..\Comum\VO\UnidadeProdutoVO.pas',
  AlmoxarifadoVO in '..\..\Comum\VO\AlmoxarifadoVO.pas',
  TributGrupoTributarioVO in '..\..\Comum\VO\TributGrupoTributarioVO.pas',
  ColaboradorController in '..\Cadastros Base\Controller\ColaboradorController.pas',
  TipoAdmissaoVO in '..\..\Comum\VO\TipoAdmissaoVO.pas',
  SituacaoColaboradorVO in '..\..\Comum\VO\SituacaoColaboradorVO.pas',
  ProdutoController in '..\Cadastros Base\Controller\ProdutoController.pas',
  UCompraTipoPedido in 'Tela\UCompraTipoPedido.pas' {FCompraTipoPedido},
  CompraTipoPedidoVO in '..\..\Comum\VO\CompraTipoPedidoVO.pas',
  UCompraPedido in 'Tela\UCompraPedido.pas' {FCompraPedido},
  CompraPedidoDetalheVO in '..\..\Comum\VO\CompraPedidoDetalheVO.pas',
  CompraPedidoVO in '..\..\Comum\VO\CompraPedidoVO.pas',
  FornecedorVO in '..\..\Comum\VO\FornecedorVO.pas',
  AtividadeForCliVO in '..\..\Comum\VO\AtividadeForCliVO.pas',
  SituacaoForCliVO in '..\..\Comum\VO\SituacaoForCliVO.pas',
  FornecedorController in '..\Cadastros Base\Controller\FornecedorController.pas',
  UCompraCotacao in 'Tela\UCompraCotacao.pas' {FCompraCotacao},
  CompraCotacaoVO in '..\..\Comum\VO\CompraCotacaoVO.pas',
  CompraFornecedorCotacaoVO in '..\..\Comum\VO\CompraFornecedorCotacaoVO.pas',
  CompraCotacaoDetalheVO in '..\..\Comum\VO\CompraCotacaoDetalheVO.pas',
  CompraCotacaoController in 'Controller\CompraCotacaoController.pas',
  CompraFornecedorCotacaoController in 'Controller\CompraFornecedorCotacaoController.pas',
  CompraPedidoController in 'Controller\CompraPedidoController.pas',
  CompraPedidoDetalheController in 'Controller\CompraPedidoDetalheController.pas',
  CompraRequisicaoController in 'Controller\CompraRequisicaoController.pas',
  CompraTipoPedidoController in 'Controller\CompraTipoPedidoController.pas',
  CompraTipoRequisicaoController in 'Controller\CompraTipoRequisicaoController.pas',
  AdministrativoFormularioVO in '..\..\Comum\VO\AdministrativoFormularioVO.pas',
  ColaboradorPessoaVO in '..\..\Comum\VO\ColaboradorPessoaVO.pas',
  CompraRequisicaoDetalheController in 'Controller\CompraRequisicaoDetalheController.pas',
  CompraReqCotacaoDetalheVO in '..\..\Comum\VO\CompraReqCotacaoDetalheVO.pas',
  FornecedorPessoaVO in '..\..\Comum\VO\FornecedorPessoaVO.pas',
  CompraCotacaoDetalheController in 'Controller\CompraCotacaoDetalheController.pas',
  ViewCompraRequisicaoItemCotadoController in 'Controller\ViewCompraRequisicaoItemCotadoController.pas',
  ViewCompraRequisicaoItemCotadoVO in '..\..\Comum\VO\ViewCompraRequisicaoItemCotadoVO.pas',
  UCompraConfirmaCotacao in 'Tela\UCompraConfirmaCotacao.pas' {FCompraConfirmaCotacao},
  CompraConfirmaFornecedorCotacaoVO in '..\..\Comum\VO\CompraConfirmaFornecedorCotacaoVO.pas',
  ViewCompraMapaComparativoVO in '..\..\Comum\VO\ViewCompraMapaComparativoVO.pas',
  ViewCompraMapaComparativoController in 'Controller\ViewCompraMapaComparativoController.pas',
  UCompraMapaComparativo in 'Tela\UCompraMapaComparativo.pas' {FCompraMapaComparativo},
  CompraCotacaoPedidoDetalheVO in '..\..\Comum\VO\CompraCotacaoPedidoDetalheVO.pas',
  UCriterioCompraSugerida in 'Tela\UCriterioCompraSugerida.pas' {FCriterioCompraSugerida},
  EmpresaSessaoVO in '..\..\Comum\VO\EmpresaSessaoVO.pas',
  ViewSessaoEmpresaVO in '..\..\Comum\VO\ViewSessaoEmpresaVO.pas',
  EmpresaController in '..\Comum\Controller\EmpresaController.pas',
  ViewSessaoEmpresaController in '..\Comum\Controller\ViewSessaoEmpresaController.pas',
  FinLancamentoPagarController in '..\Contas a Pagar\Controller\FinLancamentoPagarController.pas',
  FinLancamentoPagarVO in '..\..\Comum\VO\FinLancamentoPagarVO.pas',
  FinParcelaPagarVO in '..\..\Comum\VO\FinParcelaPagarVO.pas',
  FinLctoPagarNtFinanceiraVO in '..\..\Comum\VO\FinLctoPagarNtFinanceiraVO.pas',
  NaturezaFinanceiraVO in '..\..\Comum\VO\NaturezaFinanceiraVO.pas',
  PlanoNaturezaFinanceiraVO in '..\..\Comum\VO\PlanoNaturezaFinanceiraVO.pas',
  FinDocumentoOrigemVO in '..\..\Comum\VO\FinDocumentoOrigemVO.pas',
  ContaCaixaVO in '..\..\Comum\VO\ContaCaixaVO.pas',
  BancoVO in '..\..\Comum\VO\BancoVO.pas',
  AgenciaBancoVO in '..\..\Comum\VO\AgenciaBancoVO.pas',
  PessoaFisicaJuridicaVO in '..\..\Comum\VO\PessoaFisicaJuridicaVO.pas',
  ProdutoMarcaVO in '..\..\Comum\VO\ProdutoMarcaVO.pas',
  ProdutoLoteVO in '..\..\Comum\VO\ProdutoLoteVO.pas',
  ProdutoSubGrupoVO in '..\..\Comum\VO\ProdutoSubGrupoVO.pas',
  ProdutoGrupoVO in '..\..\Comum\VO\ProdutoGrupoVO.pas',
  TributIcmsCustomCabVO in '..\..\Comum\VO\TributIcmsCustomCabVO.pas',
  TributIcmsCustomDetVO in '..\..\Comum\VO\TributIcmsCustomDetVO.pas',
  PlanoContaRefSpedVO in '..\..\Comum\VO\PlanoContaRefSpedVO.pas',
  PlanoContaVO in '..\..\Comum\VO\PlanoContaVO.pas',
  AdmParametroVO in '..\..\Comum\VO\AdmParametroVO.pas',
  AdmParametroController in '..\Comum\Controller\AdmParametroController.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'T2Ti ERP Compras';
  Application.CreateForm(TFMenu, FMenu);
  Application.CreateForm(TFDataModule, FDataModule);
  Application.Run;
end.
