program EscritaFiscal;

uses
  Forms,
  Windows,
  Dialogs,
  Tipos in '..\Comum\Tipos.pas',
  Conversor in '..\Comum\Conversor.pas',
  NotificationService in '..\Comum\NotificationService.pas',
  SessaoUsuario in '..\Comum\SessaoUsuario.pas',
  UsuarioController in '..\Comum\Controller\UsuarioController.pas',
  Controller in '..\Comum\Controller\Controller.pas',
  FuncaoController in '..\Comum\Controller\FuncaoController.pas',
  PapelController in '..\Comum\Controller\PapelController.pas',
  PapelFuncaoController in '..\Comum\Controller\PapelFuncaoController.pas',
  UTelaCadastro in '..\Comum\Tela\UTelaCadastro.pas' {FTelaCadastro},
  UTela in '..\Comum\Tela\UTela.pas' {FTela},
  ULookup in '..\Comum\Tela\ULookup.pas' {FLookup},
  UBase in '..\Comum\Tela\UBase.pas' {FBase},
  UDataModule in '..\Comum\Tela\UDataModule.pas' {FDataModule: TDataModule},
  UFiltro in '..\Comum\Tela\UFiltro.pas' {FFiltro},
  ULogin in '..\Comum\Tela\ULogin.pas' {FLogin},
  UMenu in 'Tela\UMenu.pas' {FMenu},
  Atributos in '..\..\Comum\Atributos.pas',
  Biblioteca in '..\..\Comum\Biblioteca.pas',
  Constantes in '..\..\Comum\Constantes.pas',
  FuncaoVO in '..\..\Comum\VO\FuncaoVO.pas',
  JSonVO in '..\..\Comum\VO\JSonVO.pas',
  UsuarioVO in '..\..\Comum\VO\UsuarioVO.pas',
  PapelVO in '..\..\Comum\VO\PapelVO.pas',
  PapelFuncaoVO in '..\..\Comum\VO\PapelFuncaoVO.pas',
  PessoaVO in '..\..\Comum\VO\PessoaVO.pas',
  EnderecoVO in '..\..\Comum\VO\EnderecoVO.pas',
  ContatoVO in '..\..\Comum\VO\ContatoVO.pas',
  PessoaFisicaVO in '..\..\Comum\VO\PessoaFisicaVO.pas',
  PessoaJuridicaVO in '..\..\Comum\VO\PessoaJuridicaVO.pas',
  ColaboradorVO in '..\..\Comum\VO\ColaboradorVO.pas',
  SetorVO in '..\..\Comum\VO\SetorVO.pas',
  CargoVO in '..\..\Comum\VO\CargoVO.pas',
  EmpresaVO in '..\..\Comum\VO\EmpresaVO.pas',
  UfVO in '..\..\Comum\VO\UfVO.pas',
  PaisVO in '..\..\Comum\VO\PaisVO.pas',
  ContadorVO in '..\..\Comum\VO\ContadorVO.pas',
  FpasVO in '..\..\Comum\VO\FpasVO.pas',
  SindicatoVO in '..\..\Comum\VO\SindicatoVO.pas',
  NivelFormacaoVO in '..\..\Comum\VO\NivelFormacaoVO.pas',
  TipoColaboradorVO in '..\..\Comum\VO\TipoColaboradorVO.pas',
  SituacaoColaboradorVO in '..\..\Comum\VO\SituacaoColaboradorVO.pas',
  TipoAdmissaoVO in '..\..\Comum\VO\TipoAdmissaoVO.pas',
  RegistroCartorioController in 'Controller\RegistroCartorioController.pas',
  URegistroCartorio in 'Tela\URegistroCartorio.pas' {FRegistroCartorio},
  RegistroCartorioVO in '..\..\Comum\VO\RegistroCartorioVO.pas',
  IndiceEconomicoVO in '..\..\Comum\VO\IndiceEconomicoVO.pas',
  IndiceEconomicoController in 'Controller\IndiceEconomicoController.pas',
  TipoNotaFiscalController in 'Controller\TipoNotaFiscalController.pas',
  TipoNotaFiscalVO in '..\..\Comum\VO\TipoNotaFiscalVO.pas',
  UTipoNotaFiscal in 'Tela\UTipoNotaFiscal.pas' {FTipoNotaFiscal},
  FiscalLivroVO in '..\..\Comum\VO\FiscalLivroVO.pas',
  FiscalTermoVO in '..\..\Comum\VO\FiscalTermoVO.pas',
  FiscalLivroController in 'Controller\FiscalLivroController.pas',
  UFiscalLivro in 'Tela\UFiscalLivro.pas' {FFiscalLivro},
  UFiscalInformativosGuias in 'Tela\UFiscalInformativosGuias.pas' {FFiscalInformativosGuias},
  UFiscalApuracao in 'Tela\UFiscalApuracao.pas' {FFiscalApuracao},
  UTabelasSimplesNacional in 'Tela\UTabelasSimplesNacional.pas' {FTabelasSimplesNacional},
  SimplesNacionalCabecalhoController in 'Controller\SimplesNacionalCabecalhoController.pas',
  SimplesNacionalDetalheVO in '..\..\Comum\VO\SimplesNacionalDetalheVO.pas',
  SimplesNacionalCabecalhoVO in '..\..\Comum\VO\SimplesNacionalCabecalhoVO.pas',
  PessoaController in 'Controller\PessoaController.pas',
  EnderecoController in 'Controller\EnderecoController.pas',
  FiscalParametrosController in 'Controller\FiscalParametrosController.pas',
  FiscalParametrosVO in '..\..\Comum\VO\FiscalParametrosVO.pas',
  FiscalEstadualRegimeVO in '..\..\Comum\VO\FiscalEstadualRegimeVO.pas',
  FiscalInscricoesSubstitutasVO in '..\..\Comum\VO\FiscalInscricoesSubstitutasVO.pas',
  UFiscalParametros in 'Tela\UFiscalParametros.pas' {FFiscalParametros},
  EmpresaController in '..\Comum\Controller\EmpresaController.pas',
  ViewSessaoEmpresaController in '..\Comum\Controller\ViewSessaoEmpresaController.pas',
  AdministrativoFormularioVO in '..\..\Comum\VO\AdministrativoFormularioVO.pas',
  EmpresaSessaoVO in '..\..\Comum\VO\EmpresaSessaoVO.pas',
  ViewSessaoEmpresaVO in '..\..\Comum\VO\ViewSessaoEmpresaVO.pas',
  FiscalApuracaoIcmsController in 'Controller\FiscalApuracaoIcmsController.pas',
  FiscalApuracaoIcmsVO in '..\..\Comum\VO\FiscalApuracaoIcmsVO.pas',
  FiscalEstadualPorteVO in '..\..\Comum\VO\FiscalEstadualPorteVO.pas',
  FiscalNotaFiscalEntradaController in 'Controller\FiscalNotaFiscalEntradaController.pas',
  FiscalNotaFiscalEntradaVO in '..\..\Comum\VO\FiscalNotaFiscalEntradaVO.pas',
  FiscalNotaFiscalSaidaVO in '..\..\Comum\VO\FiscalNotaFiscalSaidaVO.pas',
  FiscalNotaFiscalSaidaController in 'Controller\FiscalNotaFiscalSaidaController.pas',
  ContabilContaVO in '..\..\Comum\VO\ContabilContaVO.pas',
  PlanoContaVO in '..\..\Comum\VO\PlanoContaVO.pas',
  PlanoContaRefSpedVO in '..\..\Comum\VO\PlanoContaRefSpedVO.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'T2Ti ERP Escrita Fiscal';
  Application.CreateForm(TFMenu, FMenu);
  Application.CreateForm(TFDataModule, FDataModule);
  Application.Run;
end.
